import type { SimulationDefinition } from "@/lib/types";

export const agentSimulation: SimulationDefinition = {
  id: "agent",
  nodes: [
    {
      id: "user",
      label: "User goal",
      subtitle: "Restart the checkout deploy",
      x: 10,
      y: 22,
      kind: "client",
      inspector: {
        what: "An intention in language. Not a command the cluster understands.",
        receives: "A human sentence.",
        returns: "A goal for the agent runtime.",
        why: "The danger is treating this string as already-authorized action.",
        related: [
          { label: "AI agent", slug: "ai-agent" },
          { label: "Identity", slug: "identity" },
        ],
      },
    },
    {
      id: "agent",
      label: "Agent runtime",
      subtitle: "the loop",
      x: 32,
      y: 22,
      kind: "runtime",
      inspector: {
        what: "Hosts the loop: think → maybe act → observe. The model is one step inside it.",
        receives: "A goal, memory, and tool results.",
        returns: "A final message, or another tool request.",
        why: "This process is the program. The LLM is not.",
        related: [
          { label: "Reasoning loop", slug: "reasoning-loop" },
          { label: "Agent runtime", slug: "agent-runtime" },
        ],
      },
    },
    {
      id: "llm",
      label: "Model",
      subtitle: "reasoning only",
      x: 54,
      y: 22,
      kind: "gpu",
      inspector: {
        what: "Produces tokens: a thought, or a structured tool call. It cannot touch prod.",
        receives: "A prompt with tools and observations.",
        returns: "Text or a function-call object.",
        why: "A thought is not an action. If this box can kubectl, you skipped the runtime.",
        related: [
          { label: "Function calling", slug: "function-calling" },
          { label: "Inference", slug: "inference" },
        ],
      },
    },
    {
      id: "authz",
      label: "Authorization",
      subtitle: "identity + policy",
      x: 54,
      y: 56,
      kind: "identity",
      inspector: {
        what: "Decides whether this agent, as this principal, may call that tool.",
        receives: "A proposed function call.",
        returns: "Allow or deny — before anything external happens.",
        why: "The model will eventually ask for something dumb. This is the adult.",
        related: [
          { label: "Tool permissions", slug: "tool-permissions" },
          { label: "Guardrails", slug: "guardrails" },
        ],
      },
    },
    {
      id: "mcp",
      label: "MCP / tool server",
      subtitle: "external world",
      x: 76,
      y: 56,
      kind: "gateway",
      inspector: {
        what: "The process that actually talks to Kubernetes, GitHub, or a browser.",
        receives: "An authorized tool request.",
        returns: "An observation: stdout, an API body, an error.",
        why: "This is the only box that has side effects.",
        related: [{ label: "MCP", slug: "mcp" }, { label: "Tools", slug: "tools" }],
      },
    },
    {
      id: "cluster",
      label: "Action",
      subtitle: "kubectl rollout",
      x: 76,
      y: 22,
      kind: "server",
      inspector: {
        what: "Real infrastructure changing. Not a token. Not a thought.",
        receives: "A tool invocation.",
        returns: "A cluster event.",
        why: "If you cannot tell this apart from reasoning, you cannot operate agents.",
        related: [
          { label: "Deployment", slug: "deployment" },
          { label: "Agent tracing", slug: "agent-tracing" },
        ],
      },
    },
    {
      id: "reply",
      label: "Final reply",
      subtitle: "to the user",
      x: 32,
      y: 56,
      kind: "client",
      inspector: {
        what: "Language again — after the loop has observations, not before.",
        receives: "The last model message.",
        returns: "Words the human can check.",
        why: "A confident paragraph is not proof the rollout happened.",
        related: [{ label: "Evaluations", slug: "evaluations" }],
      },
    },
  ],
  edges: [
    { id: "u-a", from: "user", to: "agent" },
    { id: "a-l", from: "agent", to: "llm", bidirectional: true },
    { id: "l-z", from: "llm", to: "authz" },
    { id: "z-m", from: "authz", to: "mcp" },
    { id: "m-c", from: "mcp", to: "cluster" },
    { id: "c-m", from: "cluster", to: "mcp" },
    { id: "m-a", from: "mcp", to: "agent" },
    { id: "a-r", from: "agent", to: "reply" },
  ],
  zones: [
    {
      id: "think",
      label: "Reasoning — no side effects",
      x: 22,
      y: 8,
      width: 46,
      height: 28,
      kind: "control",
    },
    {
      id: "act",
      label: "Action — the outside world",
      x: 46,
      y: 42,
      width: 48,
      height: 30,
      kind: "public",
    },
  ],
  initialStates: {
    user: { status: "goal stated" },
    agent: { status: "idle" },
    llm: { status: "not thinking" },
    authz: { status: "idle" },
    mcp: { status: "idle" },
    cluster: { status: "untouched" },
    reply: { status: "—" },
  },
  steps: [
    {
      id: "goal",
      title: "A goal, not a command",
      explanation: "The user said what they want. Nothing in the cluster has moved.",
      duration: 2200,
      events: [
        { type: "highlight", nodeIds: ["user", "agent"] },
        {
          type: "packet",
          from: "user",
          to: "agent",
          label: "Restart checkout deploy",
          kind: "prompt",
          duration: 800,
        },
        { type: "state", nodeId: "agent", patch: { status: "loop started" }, delay: 850 },
      ],
    },
    {
      id: "think",
      title: "Model reasons",
      explanation: "Purple is thought. The model chooses a tool. It has not called it.",
      duration: 2600,
      events: [
        { type: "highlight", nodeIds: ["agent", "llm"] },
        {
          type: "packet",
          from: "agent",
          to: "llm",
          label: "messages + tools",
          kind: "prompt",
          duration: 800,
        },
        { type: "state", nodeId: "llm", patch: { status: "reasoning" }, delay: 850 },
        {
          type: "packet",
          from: "llm",
          to: "agent",
          label: "tool: rollout_restart",
          kind: "token",
          delay: 1000,
          duration: 900,
        },
        {
          type: "explain",
          text: "That JSON is still just tokens. Side effects have not happened.",
          delay: 1100,
        },
      ],
    },
    {
      id: "authz",
      title: "Authorization",
      explanation: "The runtime asks policy: may this identity restart that deploy?",
      duration: 2500,
      events: [
        { type: "highlight", nodeIds: ["llm", "authz"] },
        {
          type: "packet",
          from: "llm",
          to: "authz",
          label: "propose rollout_restart",
          kind: "control",
          duration: 800,
        },
        { type: "state", nodeId: "authz", patch: { status: "allow  agent:sre" }, delay: 850 },
        {
          type: "explain",
          text: "Deny would stop here. The model does not get a second vote.",
          delay: 900,
        },
      ],
    },
    {
      id: "tool",
      title: "Tool executes",
      explanation: "Only now does an external action fire. Different color. Different zone.",
      duration: 2800,
      events: [
        { type: "highlight", nodeIds: ["authz", "mcp", "cluster"] },
        {
          type: "packet",
          from: "authz",
          to: "mcp",
          label: "call rollout_restart",
          kind: "http",
          duration: 800,
        },
        {
          type: "packet",
          from: "mcp",
          to: "cluster",
          label: "kubectl rollout restart",
          kind: "data",
          delay: 850,
          duration: 900,
        },
        { type: "state", nodeId: "cluster", patch: { status: "rollout triggered" }, delay: 1750 },
        { type: "state", nodeId: "mcp", patch: { status: "side effect" }, delay: 1750 },
        {
          type: "explain",
          text: "This hop is the one you audit. The thought is not.",
          delay: 1800,
        },
      ],
    },
    {
      id: "observe",
      title: "Observation returns",
      explanation: "The world answers. The model has not spoken to the user yet.",
      duration: 2500,
      events: [
        { type: "highlight", nodeIds: ["cluster", "mcp", "agent"] },
        {
          type: "packet",
          from: "cluster",
          to: "mcp",
          label: "deployment.apps/checkout restarted",
          kind: "response",
          duration: 800,
        },
        {
          type: "packet",
          from: "mcp",
          to: "agent",
          label: "observation",
          kind: "response",
          delay: 850,
          duration: 800,
        },
        { type: "state", nodeId: "agent", patch: { status: "got result" }, delay: 1650 },
      ],
    },
    {
      id: "think2",
      title: "Model reasons again",
      explanation: "Second thought pass. Still no extra kubectl unless policy allows it.",
      duration: 2500,
      events: [
        { type: "highlight", nodeIds: ["agent", "llm"] },
        {
          type: "packet",
          from: "agent",
          to: "llm",
          label: "observation + goal",
          kind: "prompt",
          duration: 800,
        },
        {
          type: "packet",
          from: "llm",
          to: "agent",
          label: "final: done",
          kind: "token",
          delay: 900,
          duration: 800,
        },
        { type: "state", nodeId: "llm", patch: { status: "done thinking" }, delay: 1700 },
      ],
    },
    {
      id: "final",
      title: "Reply to the user",
      explanation: "Words last. Proof was the observation, not the sentence.",
      duration: 2600,
      events: [
        { type: "highlight", nodeIds: ["agent", "reply"] },
        {
          type: "packet",
          from: "agent",
          to: "reply",
          label: "Checkout rollout restarted",
          kind: "response",
          duration: 800,
        },
        { type: "state", nodeId: "reply", patch: { status: "spoken" }, delay: 850 },
        {
          type: "explain",
          text: "Reasoning is purple. Action is the cluster hop. Never let those two look the same.",
          delay: 900,
        },
      ],
    },
  ],
};
