import type { SimulationDefinition } from "@/lib/types";

export const aiPlatformSimulation: SimulationDefinition = {
  id: "ai-platform",
  nodes: [
    {
      id: "dev",
      label: "Developer",
      subtitle: "Deploy model",
      x: 8,
      y: 20,
      kind: "client",
      inspector: {
        what: "Asks for an endpoint, not a GPU node list.",
        receives: "A checkpoint name and a traffic target.",
        returns: "A URL and a dashboard.",
        why: "Same IDP idea. New scarce resource: HBM.",
        related: [
          { label: "AI developer platform", slug: "ai-developer-platform" },
          { label: "Model deployment", slug: "model-deployment" },
        ],
      },
    },
    {
      id: "portal",
      label: "AI portal",
      subtitle: "self-service",
      x: 28,
      y: 20,
      kind: "client",
      inspector: {
        what: "Catalog of models, evals, spend. The lobby.",
        receives: "Deploy llama-70b / checkout.",
        returns: "A job on the platform API.",
        why: "Without this, every team invents a notebook-to-prod ritual.",
        related: [{ label: "Model registry", slug: "ai-model-registry" }],
      },
    },
    {
      id: "api",
      label: "Platform API",
      subtitle: "control plane",
      x: 48,
      y: 20,
      kind: "gateway",
      inspector: {
        what: "Auth, quotas, routing policy, who pays.",
        receives: "DeployModel.",
        returns: "A rollout across registry, Kubernetes, and the gateway.",
        why: "This is where cost and reliability get a contract.",
        related: [
          { label: "AI cost management", slug: "ai-cost-management" },
          { label: "Model routing", slug: "model-routing" },
        ],
      },
    },
    {
      id: "reg",
      label: "Model registry",
      subtitle: "approved checkpoints",
      x: 68,
      y: 20,
      kind: "storage",
      inspector: {
        what: "Versioned weights plus a promotion state.",
        receives: "A pin to sha / tag.",
        returns: "Bytes the GPU nodes may pull.",
        why: "You cannot roll back a vibe. You roll back a digest.",
        related: [{ label: "Model checkpoint", slug: "checkpoint" }],
      },
    },
    {
      id: "k8s",
      label: "Kubernetes",
      subtitle: "GPU scheduling",
      x: 88,
      y: 20,
      kind: "control",
      inspector: {
        what: "Places pods that request nvidia.com/gpu onto the fleet.",
        receives: "A serving Deployment.",
        returns: "A bound GPU node.",
        why: "The assignment board now has oven icons.",
        related: [
          { label: "Kubernetes GPU scheduling", slug: "k8s-gpu-scheduling" },
          { label: "GPU fleet", slug: "gpu-fleet" },
        ],
      },
    },
    {
      id: "gpu",
      label: "GPU nodes",
      subtitle: "HBM + kernels",
      x: 88,
      y: 52,
      kind: "gpu",
      inspector: {
        what: "Where weights live and tokens are born.",
        receives: "A pulled image + checkpoint.",
        returns: "Compute, until KV cache fills.",
        why: "This is the expensive floor. Everything above exists to keep it fed and shared.",
        related: [{ label: "VRAM", slug: "vram" }, { label: "Utilization", slug: "utilization" }],
      },
    },
    {
      id: "vllm",
      label: "Inference server",
      subtitle: "vLLM",
      x: 68,
      y: 52,
      kind: "runtime",
      inspector: {
        what: "The process that batches, caches KV, and streams tokens.",
        receives: "Routed HTTP.",
        returns: "A token stream.",
        why: "The application never talks to CUDA.",
        related: [{ label: "vLLM", slug: "vllm" }, { label: "KV cache", slug: "kv-cache" }],
      },
    },
    {
      id: "gw",
      label: "AI gateway",
      subtitle: "apps call this",
      x: 48,
      y: 52,
      kind: "gateway",
      inspector: {
        what: "Stable URL, auth, routing, spend limits.",
        receives: "POST /v1/chat from an app.",
        returns: "A stream from some replica.",
        why: "Apps bind to a name, not a GPU UUID.",
        related: [
          { label: "Inference gateway", slug: "inference-gateway" },
          { label: "Model endpoint", slug: "model-endpoint" },
        ],
      },
    },
    {
      id: "app",
      label: "Application",
      subtitle: "checkout UI",
      x: 28,
      y: 52,
      kind: "server",
      inspector: {
        what: "The product. It should not know about MIG or tensor parallel.",
        receives: "A user prompt.",
        returns: "A streamed answer.",
        why: "If this file contains a node selector, the platform leaked.",
        related: [{ label: "Model endpoint", slug: "model-endpoint" }],
      },
    },
    {
      id: "otel",
      label: "OpenTelemetry",
      subtitle: "tokens · traces · $",
      x: 8,
      y: 52,
      kind: "control",
      inspector: {
        what: "The same three signals, plus token counts and GPU util.",
        receives: "Spans from gateway and engine.",
        returns: "A way to debug a bad answer that still returned 200.",
        why: "A checkout can be fast and wrong. CPU graphs will not tell you.",
        related: [
          { label: "Model observability", slug: "model-observability" },
          { label: "Prompt / request observability", slug: "prompt-observability" },
        ],
      },
    },
  ],
  edges: [
    { id: "d-p", from: "dev", to: "portal" },
    { id: "p-a", from: "portal", to: "api" },
    { id: "a-r", from: "api", to: "reg" },
    { id: "a-k", from: "api", to: "k8s" },
    { id: "k-g", from: "k8s", to: "gpu" },
    { id: "r-v", from: "reg", to: "vllm" },
    { id: "g-v", from: "gpu", to: "vllm" },
    { id: "v-w", from: "vllm", to: "gw", bidirectional: true },
    { id: "w-app", from: "gw", to: "app", bidirectional: true },
    { id: "app-o", from: "app", to: "otel" },
    { id: "w-o", from: "gw", to: "otel" },
  ],
  zones: [
    { id: "cp", label: "Control plane", x: 18, y: 8, width: 62, height: 26, kind: "control" },
    { id: "dp", label: "Data plane", x: 18, y: 40, width: 80, height: 28, kind: "vram" },
  ],
  initialStates: {
    dev: { status: "wants an endpoint" },
    portal: { status: "catalog" },
    api: { status: "idle" },
    reg: { status: "llama-70b@v3" },
    k8s: { status: "idle" },
    gpu: { status: "empty" },
    vllm: { status: "not scheduled" },
    gw: { status: "no route" },
    app: { status: "blocked" },
    otel: { status: "waiting" },
  },
  steps: [
    {
      id: "ask",
      title: "Deploy a model",
      explanation: "The developer asks the portal — not the GPU team chat.",
      duration: 2200,
      events: [
        { type: "highlight", nodeIds: ["dev", "portal"] },
        {
          type: "packet",
          from: "dev",
          to: "portal",
          label: "Deploy llama-70b",
          kind: "control",
          duration: 800,
        },
      ],
    },
    {
      id: "api",
      title: "Platform API",
      explanation: "Quotas, identity, and which checkpoint is allowed in prod.",
      duration: 2300,
      events: [
        { type: "highlight", nodeIds: ["portal", "api"] },
        {
          type: "packet",
          from: "portal",
          to: "api",
          label: "POST /models/deploy",
          kind: "http",
          duration: 800,
        },
        { type: "state", nodeId: "api", patch: { status: "admitted" }, delay: 850 },
      ],
    },
    {
      id: "reg",
      title: "Pin a checkpoint",
      explanation: "The registry is the menu. v3 is what may run.",
      duration: 2300,
      events: [
        { type: "highlight", nodeIds: ["api", "reg"] },
        {
          type: "packet",
          from: "api",
          to: "reg",
          label: "pin v3",
          kind: "control",
          duration: 800,
        },
        { type: "state", nodeId: "reg", patch: { status: "serving v3" }, delay: 850 },
      ],
    },
    {
      id: "sched",
      title: "Schedule GPUs",
      explanation: "Kubernetes places a pod that requested a device. The fleet is a hangar.",
      duration: 2500,
      events: [
        { type: "highlight", nodeIds: ["api", "k8s", "gpu"] },
        {
          type: "packet",
          from: "api",
          to: "k8s",
          label: "Deployment  nvidia.com/gpu: 1",
          kind: "control",
          duration: 800,
        },
        {
          type: "packet",
          from: "k8s",
          to: "gpu",
          label: "bind node-gpu-12",
          kind: "control",
          delay: 850,
          duration: 800,
        },
        { type: "state", nodeId: "gpu", patch: { status: "reserved" }, delay: 1650 },
      ],
    },
    {
      id: "load",
      title: "Load the engine",
      explanation: "Weights land in VRAM. vLLM is warm. Still no app traffic.",
      duration: 2500,
      events: [
        { type: "highlight", nodeIds: ["reg", "gpu", "vllm"] },
        {
          type: "packet",
          from: "reg",
          to: "vllm",
          label: "pull checkpoint",
          kind: "data",
          duration: 900,
        },
        { type: "state", nodeId: "vllm", patch: { status: "ready" }, delay: 950 },
        { type: "state", nodeId: "gpu", patch: { status: "weights hot", util: 8 }, delay: 950 },
      ],
    },
    {
      id: "route",
      title: "Gateway gets a route",
      explanation: "The app’s URL now points at a live engine.",
      duration: 2300,
      events: [
        { type: "highlight", nodeIds: ["vllm", "gw", "app"] },
        {
          type: "packet",
          from: "vllm",
          to: "gw",
          label: "register replica",
          kind: "control",
          duration: 800,
        },
        { type: "state", nodeId: "gw", patch: { status: "/v1/chat → v3" }, delay: 850 },
        { type: "state", nodeId: "app", patch: { status: "can call" }, delay: 850 },
      ],
    },
    {
      id: "traffic",
      title: "A real prompt",
      explanation: "The product talks to the gateway. Tokens stream. The GPU util moves.",
      duration: 2600,
      events: [
        { type: "highlight", nodeIds: ["app", "gw", "vllm", "gpu"] },
        {
          type: "packet",
          from: "app",
          to: "gw",
          label: "POST /v1/chat",
          kind: "prompt",
          duration: 700,
        },
        {
          type: "packet",
          from: "gw",
          to: "vllm",
          label: "generate",
          kind: "prompt",
          delay: 750,
          duration: 700,
        },
        { type: "state", nodeId: "gpu", patch: { status: "decode", util: 61 }, delay: 1500 },
        {
          type: "packet",
          from: "vllm",
          to: "gw",
          label: "tokens",
          kind: "token",
          delay: 1600,
          duration: 700,
        },
      ],
    },
    {
      id: "obs",
      title: "Observe the same call",
      explanation: "Traces, token counts, GPU util, cost. The stack is one system again.",
      duration: 2800,
      events: [
        { type: "highlight", nodeIds: ["app", "gw", "otel"] },
        {
          type: "packet",
          from: "gw",
          to: "otel",
          label: "span + tokens=84",
          kind: "data",
          duration: 800,
        },
        {
          type: "packet",
          from: "app",
          to: "otel",
          label: "trace 8f21",
          kind: "data",
          delay: 200,
          duration: 800,
        },
        { type: "state", nodeId: "otel", patch: { status: "metrics/traces/logs" }, delay: 1050 },
        {
          type: "explain",
          text: "Portal to GPU to traces. That is the whole curriculum on one path.",
          delay: 1100,
        },
      ],
    },
  ],
};
