import type { SimulationDefinition } from "@/lib/types";

export const cicdSimulation: SimulationDefinition = {
  id: "cicd",
  nodes: [
    {
      id: "dev",
      label: "Developer",
      subtitle: "git commit",
      x: 10,
      y: 22,
      kind: "client",
      inspector: {
        what: "A person with a working tree. The pipeline does not run on their laptop’s folder.",
        receives: "An idea and a diff.",
        returns: "A commit hash.",
        why: "CI is triggered by history, not by hope.",
        related: [{ label: "Commit", slug: "commit" }, { label: "Repository", slug: "repository" }],
      },
    },
    {
      id: "gh",
      label: "GitHub",
      subtitle: "the ledger",
      x: 32,
      y: 22,
      kind: "storage",
      inspector: {
        what: "The remote history. A push here is the event.",
        receives: "A commit on a branch.",
        returns: "A webhook to CI.",
        why: "If it is not in the repo, the pipeline never saw it.",
        related: [{ label: "Branch", slug: "branch" }, { label: "CI", slug: "ci" }],
      },
    },
    {
      id: "ci",
      label: "CI runner",
      subtitle: "install → test → build",
      x: 54,
      y: 22,
      kind: "runtime",
      inspector: {
        what: "An ephemeral machine that replays the recipe against that SHA.",
        receives: "A job graph.",
        returns: "Pass/fail plus an artifact.",
        why: "This is how “it works on my machine” dies.",
        related: [{ label: "Pipeline", slug: "pipeline" }, { label: "Test", slug: "test" }],
      },
    },
    {
      id: "image",
      label: "Image",
      subtitle: "app@sha",
      x: 76,
      y: 22,
      kind: "storage",
      inspector: {
        what: "The immutable output of the build.",
        receives: "A successful build job.",
        returns: "A digest you can promote.",
        why: "You deploy this object, not “whatever main looks like now.”",
        related: [{ label: "Artifact", slug: "artifact" }, { label: "Image", slug: "image" }],
      },
    },
    {
      id: "reg",
      label: "Registry",
      subtitle: "ghcr / ECR",
      x: 76,
      y: 56,
      kind: "storage",
      inspector: {
        what: "Where the digest lives so prod can pull it.",
        receives: "A push.",
        returns: "The same bytes to the cluster.",
        why: "Environments should pull, not rebuild.",
        related: [{ label: "Registry", slug: "registry" }, { label: "Deployment", slug: "deployment" }],
      },
    },
    {
      id: "deploy",
      label: "Deploy system",
      subtitle: "staging → prod",
      x: 54,
      y: 56,
      kind: "control",
      inspector: {
        what: "The thing that changes a live environment to that digest.",
        receives: "A blessed artifact + a target.",
        returns: "A rollout.",
        why: "This is the blast radius. CI was only permission to arrive here.",
        related: [
          { label: "Environments", slug: "environments" },
          { label: "Progressive deployment", slug: "progressive-deployment" },
        ],
      },
    },
    {
      id: "prod",
      label: "Production",
      subtitle: "the running SHA",
      x: 32,
      y: 56,
      kind: "server",
      inspector: {
        what: "What users hit. Its only honest label is the digest.",
        receives: "A new ReplicaSet / task.",
        returns: "Traffic on the new code — or a rollback.",
        why: "Rollback means “point at yesterday’s crate,” not “rebuild main.”",
        related: [{ label: "Rollback", slug: "rollback" }, { label: "GitOps", slug: "gitops" }],
      },
    },
  ],
  edges: [
    { id: "d-g", from: "dev", to: "gh" },
    { id: "g-c", from: "gh", to: "ci" },
    { id: "c-i", from: "ci", to: "image" },
    { id: "i-r", from: "image", to: "reg" },
    { id: "r-d", from: "reg", to: "deploy" },
    { id: "d-p", from: "deploy", to: "prod" },
  ],
  zones: [
    { id: "verify", label: "Verify", x: 44, y: 8, width: 44, height: 28, kind: "control" },
    { id: "ship", label: "Ship", x: 24, y: 42, width: 64, height: 30, kind: "public" },
  ],
  initialStates: {
    dev: { status: "dirty tree" },
    gh: { status: "main @ a1" },
    ci: { status: "idle" },
    image: { status: "none" },
    reg: { status: "waiting" },
    deploy: { status: "idle" },
    prod: { status: "serving a1" },
  },
  steps: [
    {
      id: "commit",
      title: "Commit",
      explanation: "A snapshot with a parent. CI will run against this hash, not the laptop.",
      duration: 2200,
      events: [
        { type: "highlight", nodeIds: ["dev", "gh"] },
        {
          type: "packet",
          from: "dev",
          to: "gh",
          label: "push  a2  feat: checkout",
          kind: "control",
          duration: 800,
        },
        { type: "state", nodeId: "gh", patch: { status: "main @ a2" }, delay: 850 },
      ],
    },
    {
      id: "hook",
      title: "GitHub wakes CI",
      explanation: "A webhook. The runner checks out a2 — not “latest,” the exact SHA.",
      duration: 2300,
      events: [
        { type: "highlight", nodeIds: ["gh", "ci"] },
        {
          type: "packet",
          from: "gh",
          to: "ci",
          label: "workflow_dispatch a2",
          kind: "control",
          duration: 800,
        },
        { type: "state", nodeId: "ci", patch: { status: "checkout a2" }, delay: 850 },
      ],
    },
    {
      id: "install",
      title: "Install dependencies",
      explanation: "The lockfile wins. If this step is “whatever npm feels,” the artifact is a rumor.",
      duration: 2300,
      events: [
        { type: "highlight", nodeIds: ["ci"] },
        { type: "state", nodeId: "ci", patch: { status: "pnpm i --frozen" } },
      ],
    },
    {
      id: "test",
      title: "Tests",
      explanation: "If it is not in CI, it is optional — and will rot.",
      duration: 2300,
      events: [
        { type: "highlight", nodeIds: ["ci"] },
        { type: "state", nodeId: "ci", patch: { status: "test  184 passed" } },
      ],
    },
    {
      id: "build",
      title: "Build the image",
      explanation: "The crate is sealed here. Staging and prod should both pull this digest.",
      duration: 2500,
      events: [
        { type: "highlight", nodeIds: ["ci", "image"] },
        {
          type: "packet",
          from: "ci",
          to: "image",
          label: "docker build  sha256:9f3a",
          kind: "data",
          duration: 900,
        },
        { type: "state", nodeId: "image", patch: { status: "app@a2" }, delay: 950 },
      ],
    },
    {
      id: "push",
      title: "Push to the registry",
      explanation: "Promotion is a pointer. Rebuild-per-environment is how you ship two different apps.",
      duration: 2400,
      events: [
        { type: "highlight", nodeIds: ["image", "reg"] },
        {
          type: "packet",
          from: "image",
          to: "reg",
          label: "push app@a2",
          kind: "data",
          duration: 800,
        },
        { type: "state", nodeId: "reg", patch: { status: "digest stored" }, delay: 850 },
      ],
    },
    {
      id: "rollout",
      title: "Deploy production",
      explanation: "The deploy system changes live reality to that digest.",
      duration: 2600,
      events: [
        { type: "highlight", nodeIds: ["reg", "deploy", "prod"] },
        {
          type: "packet",
          from: "reg",
          to: "deploy",
          label: "pull app@a2",
          kind: "control",
          duration: 800,
        },
        {
          type: "packet",
          from: "deploy",
          to: "prod",
          label: "rollout",
          kind: "http",
          delay: 900,
          duration: 800,
        },
        { type: "state", nodeId: "prod", patch: { status: "serving a2" }, delay: 1700 },
        {
          type: "explain",
          text: "Commit → check → crate → pull. That is the whole product.",
          delay: 1750,
        },
      ],
    },
  ],
};
