import type { SimulationDefinition } from "@/lib/types";

export const cloudSimulation: SimulationDefinition = {
  id: "cloud",
  nodes: [
    {
      id: "internet",
      label: "Internet",
      subtitle: "users",
      x: 10,
      y: 22,
      kind: "network",
      inspector: {
        what: "Untrusted public clients. They only know a name.",
        receives: "A browser request.",
        returns: "Packets toward the edge.",
        why: "Everything below is how we let them in without exposing the database.",
        related: [{ label: "DNS", slug: "dns" }, { label: "HTTPS", slug: "https" }],
      },
    },
    {
      id: "r53",
      label: "Route 53",
      subtitle: "DNS",
      x: 32,
      y: 22,
      kind: "dns",
      inspector: {
        what: "AWS DNS. The name becomes a CloudFront anycast IP.",
        receives: "A lookup for the site.",
        returns: "An edge address, not the VPC.",
        why: "Users never resolve the private app.",
        related: [{ label: "DNS", slug: "dns" }, { label: "CDN", slug: "cdn" }],
      },
    },
    {
      id: "cf",
      label: "CloudFront",
      subtitle: "CDN edge",
      x: 54,
      y: 22,
      kind: "gateway",
      inspector: {
        what: "Caches and terminates TLS close to the user.",
        receives: "HTTPS at the edge.",
        returns: "A cache hit, or a fetch to the ALB.",
        why: "Most bytes should never enter the VPC.",
        related: [{ label: "CDN", slug: "cdn" }, { label: "TLS", slug: "tls" }],
      },
    },
    {
      id: "igw",
      label: "Internet gateway",
      subtitle: "VPC door",
      x: 76,
      y: 22,
      kind: "router",
      inspector: {
        what: "The VPC’s public door. Only public subnets route here.",
        receives: "Packets from the internet.",
        returns: "Forwarding into a public subnet.",
        why: "Private subnets have no path to this box.",
        related: [
          { label: "Internet gateway", slug: "internet-gateway" },
          { label: "Route table", slug: "route-table" },
        ],
      },
    },
    {
      id: "alb",
      label: "ALB",
      subtitle: "public subnet",
      x: 76,
      y: 50,
      kind: "gateway",
      inspector: {
        what: "A load balancer with a public IP, security group, and target group.",
        receives: "HTTPS from CloudFront / IGW.",
        returns: "A hop to a healthy private instance.",
        why: "This is the last public thing. Apps sit behind it.",
        related: [
          { label: "Load balancer", slug: "load-balancer" },
          { label: "Public / private subnet", slug: "public-private-subnet" },
        ],
      },
    },
    {
      id: "app",
      label: "App servers",
      subtitle: "private subnet",
      x: 54,
      y: 50,
      kind: "server",
      inspector: {
        what: "EC2 or tasks with no public IP. Outbound via NAT if needed.",
        receives: "HTTP from the ALB only.",
        returns: "Application responses.",
        why: "The security group says: ALB in, nothing else.",
        related: [
          { label: "Security groups", slug: "security-groups" },
          { label: "NAT gateway", slug: "nat-gateway" },
        ],
      },
    },
    {
      id: "rds",
      label: "RDS",
      subtitle: "private subnet",
      x: 32,
      y: 50,
      kind: "storage",
      inspector: {
        what: "A managed database with no public access.",
        receives: "Queries from the app SG.",
        returns: "Rows.",
        why: "If this has a public IP, the design already failed.",
        related: [
          { label: "Databases", slug: "databases" },
          { label: "Security groups", slug: "security-groups" },
        ],
      },
    },
    {
      id: "nat",
      label: "NAT gateway",
      subtitle: "egress only",
      x: 10,
      y: 50,
      kind: "router",
      inspector: {
        what: "Outbound internet for private subnets. No inbound.",
        receives: "App patch / API calls.",
        returns: "Replies to the same connection.",
        why: "Private does not mean “cannot call out.” It means “cannot be called.”",
        related: [
          { label: "NAT gateway", slug: "nat-gateway" },
          { label: "NAT", slug: "nat" },
        ],
      },
    },
  ],
  edges: [
    { id: "i-r", from: "internet", to: "r53", bidirectional: true },
    { id: "i-cf", from: "internet", to: "cf" },
    { id: "cf-igw", from: "cf", to: "igw" },
    { id: "igw-alb", from: "igw", to: "alb" },
    { id: "alb-app", from: "alb", to: "app", bidirectional: true },
    { id: "app-rds", from: "app", to: "rds", bidirectional: true },
    { id: "app-nat", from: "app", to: "nat" },
    { id: "nat-i", from: "nat", to: "internet" },
  ],
  zones: [
    {
      id: "public",
      label: "Public subnet",
      x: 66,
      y: 8,
      width: 30,
      height: 58,
      kind: "public",
    },
    {
      id: "private",
      label: "Private subnet",
      x: 2,
      y: 38,
      width: 62,
      height: 28,
      kind: "private",
    },
  ],
  initialStates: {
    internet: { status: "https://app.example" },
    r53: { status: "zone app.example" },
    cf: { status: "edge" },
    igw: { status: "attached" },
    alb: { status: "sg-alb  :443", subnet: "public-a" },
    app: { status: "sg-app  :8080", subnet: "private-a" },
    rds: { status: "sg-db  :5432", subnet: "private-b" },
    nat: { status: "egress" },
  },
  selectControls: [
    {
      id: "view",
      label: "Show",
      defaultValue: "request",
      options: [
        { label: "Request flow", value: "request" },
        { label: "Network boundaries", value: "network" },
        { label: "Security boundaries", value: "security" },
      ],
    },
  ],
  controlEffects: {
    view: {
      request: {
        caption: "Follow the request: name → edge → public ALB → private app → private RDS.",
        states: {
          internet: { status: "request in" },
          r53: { status: "name → CloudFront" },
          cf: { status: "TLS + cache" },
          alb: { status: "public hop" },
          app: { status: "handles GET" },
          rds: { status: "query" },
        },
      },
      network: {
        caption: "Public subnet has a route to the IGW. Private does not. NAT is egress-only.",
        states: {
          igw: { status: "0.0.0.0/0 from public" },
          alb: { status: "public-a  10.0.1.0/24" },
          app: { status: "private-a  10.0.2.0/24" },
          rds: { status: "private-b  10.0.3.0/24" },
          nat: { status: "private default route" },
        },
      },
      security: {
        caption: "Security groups are allow-lists: 443 to ALB, 8080 from ALB, 5432 from app.",
        states: {
          alb: { status: "sg-alb  allow :443 world" },
          app: { status: "sg-app  allow :8080 from sg-alb" },
          rds: { status: "sg-db  allow :5432 from sg-app" },
          nat: { status: "no inbound" },
        },
      },
    },
  },
  steps: [
    {
      id: "name",
      title: "A public name",
      explanation: "The user has a hostname. They must never receive the RDS address.",
      duration: 2200,
      events: [{ type: "highlight", nodeIds: ["internet", "r53"] }],
    },
    {
      id: "dns",
      title: "Route 53 answers",
      explanation: "DNS returns CloudFront, not the VPC. The origin stays hidden.",
      duration: 2400,
      events: [
        { type: "highlight", nodeIds: ["internet", "r53"] },
        {
          type: "packet",
          from: "internet",
          to: "r53",
          label: "A? app.example",
          kind: "query",
          duration: 800,
        },
        {
          type: "packet",
          from: "r53",
          to: "internet",
          label: "CloudFront anycast",
          kind: "response",
          delay: 900,
          duration: 800,
        },
      ],
    },
    {
      id: "edge",
      title: "CloudFront edge",
      explanation: "TLS dies at the edge. A cache hit would stop here.",
      duration: 2400,
      events: [
        { type: "highlight", nodeIds: ["internet", "cf"] },
        {
          type: "packet",
          from: "internet",
          to: "cf",
          label: "GET /  miss",
          kind: "http",
          duration: 900,
        },
        { type: "state", nodeId: "cf", patch: { status: "origin fetch" }, delay: 950 },
      ],
    },
    {
      id: "enter",
      title: "Enter the VPC",
      explanation: "The request crosses the internet gateway into a public subnet.",
      duration: 2400,
      events: [
        { type: "highlight", nodeIds: ["cf", "igw", "alb"] },
        {
          type: "packet",
          from: "cf",
          to: "igw",
          label: "to ALB",
          kind: "data",
          duration: 700,
        },
        {
          type: "packet",
          from: "igw",
          to: "alb",
          label: "public-a",
          kind: "data",
          delay: 750,
          duration: 700,
        },
      ],
    },
    {
      id: "alb",
      title: "ALB chooses a target",
      explanation: "The last public hop. Next packet is private.",
      duration: 2400,
      events: [
        { type: "highlight", nodeIds: ["alb", "app"] },
        {
          type: "packet",
          from: "alb",
          to: "app",
          label: "HTTP  10.0.2.20:8080",
          kind: "http",
          duration: 900,
        },
        { type: "connection", edgeId: "alb-app", open: true },
      ],
    },
    {
      id: "db",
      title: "Private query",
      explanation: "The app talks to RDS on a private route. No IGW involved.",
      duration: 2500,
      events: [
        { type: "highlight", nodeIds: ["app", "rds"] },
        {
          type: "packet",
          from: "app",
          to: "rds",
          label: "SELECT …",
          kind: "query",
          duration: 800,
        },
        {
          type: "packet",
          from: "rds",
          to: "app",
          label: "rows",
          kind: "response",
          delay: 900,
          duration: 800,
        },
      ],
    },
    {
      id: "views",
      title: "Toggle the lens",
      explanation: "Same boxes. Use Show: request, network, or security.",
      duration: 2800,
      events: [
        { type: "highlight", nodeIds: ["alb", "app", "rds", "igw", "nat"] },
        {
          type: "explain",
          text: "Public vs private is a route table. Allowed vs denied is a security group.",
        },
      ],
    },
  ],
};
