import type { SimulationDefinition } from "@/lib/types";

export const consistencySimulation: SimulationDefinition = {
  id: "consistency",
  nodes: [
    {
      id: "client",
      label: "Writer",
      subtitle: "UPDATE balance=80",
      x: 10,
      y: 28,
      kind: "client",
      inspector: {
        what: "An application that believes the write is done when the leader acks.",
        receives: "A user action.",
        returns: "“OK” — which may be ahead of the followers.",
        why: "The lie begins at the success response.",
        related: [
          { label: "Leader / follower", slug: "leader-follower" },
          { label: "Replication", slug: "replication" },
        ],
      },
    },
    {
      id: "leader",
      label: "Leader",
      subtitle: "primary",
      x: 36,
      y: 28,
      kind: "storage",
      inspector: {
        what: "The only node that takes the write first.",
        receives: "The UPDATE.",
        returns: "An ack, then a replication stream.",
        why: "One pen. Everyone else copies.",
        related: [
          { label: "Leader / follower", slug: "leader-follower" },
          { label: "Consensus basics", slug: "consensus-basics" },
        ],
      },
    },
    {
      id: "f1",
      label: "Follower A",
      subtitle: "replica",
      x: 62,
      y: 16,
      kind: "storage",
      inspector: {
        what: "A copy that applies the stream. Fast path, usually.",
        receives: "A replication record.",
        returns: "Reads that might still be old.",
        why: "Near the leader is not the same as equal to the leader.",
        related: [{ label: "Replication", slug: "replication" }],
      },
    },
    {
      id: "f2",
      label: "Follower B",
      subtitle: "delayed replica",
      x: 62,
      y: 44,
      kind: "storage",
      inspector: {
        what: "The same log, later. Cross-AZ, busy disk, or a pause.",
        receives: "The same record — after a visible wait.",
        returns: "Stale reads until it catches up.",
        why: "This delay is the lesson. Eventual is a schedule, not a vibe.",
        related: [{ label: "Eventual consistency", slug: "eventual-consistency" }],
      },
    },
    {
      id: "reader",
      label: "Reader",
      subtitle: "SELECT balance",
      x: 86,
      y: 44,
      kind: "client",
      inspector: {
        what: "Another client, maybe behind a read replica or a cache.",
        receives: "Whatever that copy currently is.",
        returns: "80 — or still 100.",
        why: "Two correct systems can disagree about “now.”",
        related: [{ label: "Caching", slug: "caching" }, { label: "Idempotency", slug: "idempotency" }],
      },
    },
    {
      id: "clock",
      label: "Time",
      subtitle: "the gap",
      x: 36,
      y: 62,
      kind: "control",
      inspector: {
        what: "The distance between the leader’s ack and the last copy applying.",
        receives: "Nothing — it just passes.",
        returns: "Convergence, if the replica is healthy.",
        why: "If you needed zero gap, you needed a quorum write, not this design.",
        related: [
          { label: "Consensus basics", slug: "consensus-basics" },
          { label: "Retries", slug: "retries" },
        ],
      },
    },
  ],
  edges: [
    { id: "c-l", from: "client", to: "leader", bidirectional: true },
    { id: "l-a", from: "leader", to: "f1" },
    { id: "l-b", from: "leader", to: "f2" },
    { id: "b-r", from: "f2", to: "reader" },
    { id: "l-t", from: "leader", to: "clock" },
    { id: "t-b", from: "clock", to: "f2" },
  ],
  zones: [
    { id: "copies", label: "Same row, three clocks", x: 26, y: 6, width: 50, height: 52, kind: "cluster" },
  ],
  initialStates: {
    client: { status: "balance=100" },
    leader: { status: "100" },
    f1: { status: "100" },
    f2: { status: "100" },
    reader: { status: "sees 100" },
    clock: { status: "in sync" },
  },
  steps: [
    {
      id: "steady",
      title: "Everyone agrees",
      explanation: "Three copies, one value. This is the easy picture — and it does not last.",
      duration: 2200,
      events: [{ type: "highlight", nodeIds: ["leader", "f1", "f2"] }],
    },
    {
      id: "write",
      title: "Write the leader",
      explanation: "The primary takes 80 and acks. The writer is told it is done.",
      duration: 2500,
      events: [
        { type: "highlight", nodeIds: ["client", "leader"] },
        {
          type: "packet",
          from: "client",
          to: "leader",
          label: "UPDATE 100 → 80",
          kind: "query",
          duration: 800,
        },
        { type: "state", nodeId: "leader", patch: { status: "80" }, delay: 850 },
        {
          type: "packet",
          from: "leader",
          to: "client",
          label: "OK",
          kind: "response",
          delay: 950,
          duration: 700,
        },
        { type: "state", nodeId: "client", patch: { status: "thinks 80" }, delay: 1650 },
      ],
    },
    {
      id: "fast",
      title: "Follower A catches up",
      explanation: "Nearby replica applies quickly. Still not instantaneous — just short.",
      duration: 2300,
      events: [
        { type: "highlight", nodeIds: ["leader", "f1"] },
        {
          type: "packet",
          from: "leader",
          to: "f1",
          label: "repl 80",
          kind: "data",
          duration: 700,
        },
        { type: "state", nodeId: "f1", patch: { status: "80" }, delay: 750 },
      ],
    },
    {
      id: "delay",
      title: "Follower B is late",
      explanation: "The record is in flight. We leave it late on purpose so you can see the gap.",
      duration: 3200,
      events: [
        { type: "highlight", nodeIds: ["leader", "clock", "f2"] },
        {
          type: "packet",
          from: "leader",
          to: "clock",
          label: "wal record",
          kind: "data",
          duration: 900,
        },
        { type: "state", nodeId: "clock", patch: { status: "lag 240ms" }, delay: 950 },
        { type: "state", nodeId: "f2", patch: { status: "still 100" }, delay: 950 },
        {
          type: "explain",
          text: "This is eventual consistency: the write succeeded, the copy has not.",
          delay: 1000,
        },
      ],
    },
    {
      id: "stale",
      title: "A read hits the late copy",
      explanation: "The reader gets 100. Nobody crashed. The system is working as designed.",
      duration: 2800,
      events: [
        { type: "highlight", nodeIds: ["reader", "f2"] },
        {
          type: "packet",
          from: "f2",
          to: "reader",
          label: "SELECT → 100",
          kind: "response",
          duration: 800,
        },
        { type: "state", nodeId: "reader", patch: { status: "stale 100" }, delay: 850 },
        { type: "latency", nodeId: "f2", ms: 240, delay: 850 },
      ],
    },
    {
      id: "catch",
      title: "Then it converges",
      explanation: "The delayed record arrives. Now all three say 80. “Eventual” meant this wait.",
      duration: 2800,
      events: [
        { type: "highlight", nodeIds: ["clock", "f2", "reader"] },
        {
          type: "packet",
          from: "clock",
          to: "f2",
          label: "apply 80",
          kind: "data",
          duration: 1000,
        },
        { type: "state", nodeId: "f2", patch: { status: "80" }, delay: 1050 },
        { type: "state", nodeId: "clock", patch: { status: "caught up" }, delay: 1050 },
        { type: "state", nodeId: "reader", patch: { status: "now 80" }, delay: 1600 },
        {
          type: "explain",
          text: "If that wait is unacceptable, you did not want this replica for that read.",
          delay: 1650,
        },
      ],
    },
  ],
};
