import type { SimulationDefinition } from "@/lib/types";

export const cpuGpuSimulation: SimulationDefinition = {
  id: "cpu-gpu",
  nodes: [
    {
      id: "work",
      label: "Work",
      subtitle: "8 matrix tiles",
      x: 12,
      y: 40,
      kind: "queue",
      inspector: {
        what: "The same kind of math, many times. That shape is the whole reason GPUs exist.",
        receives: "A batch.",
        returns: "Tiles a CPU would do one-by-one.",
        why: "If the work is serial and branchy, stay on the CPU.",
        related: [
          { label: "Parallel processing", slug: "parallel-processing" },
          { label: "Batching", slug: "batching" },
        ],
      },
    },
    {
      id: "cpu",
      label: "CPU",
      subtitle: "few wide cores",
      x: 40,
      y: 22,
      kind: "control",
      inspector: {
        what: "A handful of sophisticated cores. Great at decisions, slow at a thousand identical multiplies.",
        receives: "One tile at a time.",
        returns: "A result, then the next.",
        why: "Latency for one item can be fine. Throughput for a batch is not.",
        related: [{ label: "CPU", slug: "cpu" }, { label: "CPU vs GPU", slug: "cpu-vs-gpu" }],
      },
    },
    {
      id: "gpu",
      label: "GPU",
      subtitle: "thousands of narrow cores",
      x: 40,
      y: 62,
      kind: "gpu",
      inspector: {
        what: "A factory of identical ALUs. Same kernel, many tiles.",
        receives: "A grid of work.",
        returns: "Many results in one wave.",
        why: "Utilization dies when you send one cookie to the oven.",
        related: [
          { label: "CUDA", slug: "cuda" },
          { label: "Utilization", slug: "utilization" },
        ],
      },
    },
    {
      id: "cpu-out",
      label: "CPU done",
      subtitle: "serial",
      x: 70,
      y: 22,
      kind: "process",
      inspector: {
        what: "Eight passes later.",
        receives: "Each CPU tile.",
        returns: "The full batch — late.",
        why: "You paid for eight round trips.",
        related: [{ label: "Throughput", slug: "throughput" }],
      },
    },
    {
      id: "gpu-out",
      label: "GPU done",
      subtitle: "one wave",
      x: 70,
      y: 62,
      kind: "process",
      inspector: {
        what: "The same eight tiles, overlapped.",
        receives: "The kernel grid.",
        returns: "The batch together.",
        why: "This is why inference batches exist.",
        related: [{ label: "Batching", slug: "batching" }, { label: "Tokens/sec", slug: "tokens-sec" }],
      },
    },
  ],
  edges: [
    { id: "w-c", from: "work", to: "cpu" },
    { id: "w-g", from: "work", to: "gpu" },
    { id: "c-o", from: "cpu", to: "cpu-out" },
    { id: "g-o", from: "gpu", to: "gpu-out" },
  ],
  zones: [
    { id: "serial", label: "Serial", x: 30, y: 8, width: 54, height: 30, kind: "control" },
    { id: "parallel", label: "Parallel", x: 30, y: 48, width: 54, height: 30, kind: "vram" },
  ],
  initialStates: {
    work: { status: "8 tiles queued" },
    cpu: { status: "idle", util: 0 },
    gpu: { status: "idle", util: 0 },
    "cpu-out": { status: "0/8" },
    "gpu-out": { status: "0/8" },
  },
  steps: [
    {
      id: "split",
      title: "Same work, two shapes",
      explanation: "Eight identical tiles. Watch the CPU walk them. Watch the GPU take them at once.",
      duration: 2200,
      events: [{ type: "highlight", nodeIds: ["work", "cpu", "gpu"] }],
    },
    {
      id: "cpu1",
      title: "CPU tile 1…2…3",
      explanation: "One sophisticated core. One tile. Then another.",
      duration: 2800,
      events: [
        { type: "highlight", nodeIds: ["work", "cpu", "cpu-out"] },
        {
          type: "packet",
          from: "work",
          to: "cpu",
          label: "tile 1",
          kind: "data",
          duration: 500,
        },
        {
          type: "packet",
          from: "work",
          to: "cpu",
          label: "tile 2",
          kind: "data",
          delay: 550,
          duration: 500,
        },
        {
          type: "packet",
          from: "work",
          to: "cpu",
          label: "tile 3",
          kind: "data",
          delay: 1100,
          duration: 500,
        },
        { type: "state", nodeId: "cpu", patch: { status: "busy", util: 40 }, delay: 500 },
        { type: "state", nodeId: "cpu-out", patch: { status: "3/8" }, delay: 1700 },
      ],
    },
    {
      id: "gpu-wave",
      title: "GPU: one kernel, many tiles",
      explanation: "The same eight tiles leave together. That is a warp/grid, not a smarter CPU.",
      duration: 2600,
      events: [
        { type: "highlight", nodeIds: ["work", "gpu", "gpu-out"] },
        {
          type: "packet",
          from: "work",
          to: "gpu",
          label: "tiles 1–8",
          kind: "data",
          duration: 800,
        },
        { type: "state", nodeId: "gpu", patch: { status: "kernel", util: 88 }, delay: 850 },
        {
          type: "packet",
          from: "gpu",
          to: "gpu-out",
          label: "8 results",
          kind: "response",
          delay: 1000,
          duration: 800,
        },
        { type: "state", nodeId: "gpu-out", patch: { status: "8/8" }, delay: 1800 },
      ],
    },
    {
      id: "cpu-finish",
      title: "CPU still walking",
      explanation: "The GPU is done. The CPU is on tile 6. Throughput was the point.",
      duration: 2600,
      events: [
        { type: "highlight", nodeIds: ["cpu", "cpu-out", "gpu-out"] },
        {
          type: "packet",
          from: "cpu",
          to: "cpu-out",
          label: "tile 6",
          kind: "data",
          duration: 700,
        },
        { type: "state", nodeId: "cpu-out", patch: { status: "6/8" }, delay: 750 },
        { type: "state", nodeId: "cpu", patch: { status: "still going", util: 40 }, delay: 750 },
        {
          type: "explain",
          text: "A chef vs a factory of mixers. Inference is the factory job.",
          delay: 800,
        },
      ],
    },
  ],
};
