import type { SimulationDefinition } from "@/lib/types";

export const dnsSimulation: SimulationDefinition = {
  id: "dns",
  nodes: [
    {
      id: "browser",
      label: "Browser",
      subtitle: "platformvisualizer.dev",
      x: 10,
      y: 18,
      kind: "client",
      inspector: {
        what: "The client that needs an IP address before it can open a TCP connection.",
        receives: "A hostname typed by a human.",
        returns: "An HTTP request once it knows where to send it.",
        why: "Applications speak names. The network speaks numbers.",
        related: [
          { label: "TCP", slug: "tcp" },
          { label: "HTTP", slug: "http" },
          { label: "Sockets", slug: "sockets" },
        ],
      },
    },
    {
      id: "cache",
      label: "Local DNS cache",
      subtitle: "OS + browser",
      x: 10,
      y: 48,
      kind: "cache",
      inspector: {
        what: "A short-lived memory of recent name → IP answers.",
        receives: "A hostname lookup.",
        returns: "A cached A/AAAA record, or a miss.",
        why: "Most lookups never leave the machine. TTL decides how long the answer stays valid.",
        related: [
          { label: "TTL", slug: "dns" },
          { label: "DNS records", slug: "dns" },
        ],
      },
    },
    {
      id: "resolver",
      label: "Recursive resolver",
      subtitle: "1.1.1.1",
      x: 38,
      y: 48,
      kind: "resolver",
      inspector: {
        what: "A DNS server that performs lookups on behalf of clients.",
        receives: "A domain name.",
        returns: "An IP address or another DNS response.",
        why: "It prevents every laptop from walking the DNS hierarchy by hand.",
        related: [
          { label: "Caching", slug: "dns" },
          { label: "Root DNS", slug: "dns" },
          { label: "Authoritative DNS", slug: "dns" },
        ],
      },
    },
    {
      id: "root",
      label: "Root DNS",
      subtitle: ".",
      x: 66,
      y: 18,
      kind: "dns",
      inspector: {
        what: "The top of the DNS tree. It does not know google.com — it knows who owns .com.",
        receives: "A query for a name it does not host.",
        returns: "A referral to the correct TLD servers.",
        why: "Thirteen root server identities keep the namespace globally consistent.",
        related: [
          { label: "TLD server", slug: "dns" },
          { label: "IANA", slug: "dns" },
        ],
      },
    },
    {
      id: "tld",
      label: "TLD server",
      subtitle: ".dev",
      x: 66,
      y: 48,
      kind: "dns",
      inspector: {
        what: "The registry for a top-level domain such as .com, .dev, or .io.",
        receives: "A query for a second-level name.",
        returns: "The authoritative nameservers for that zone.",
        why: "Delegation lets millions of zones exist without one giant database.",
        related: [
          { label: "Authoritative DNS", slug: "dns" },
          { label: "Registrar", slug: "dns" },
        ],
      },
    },
    {
      id: "auth",
      label: "Authoritative DNS",
      subtitle: "ns.cloudflare.com",
      x: 66,
      y: 78,
      kind: "dns",
      inspector: {
        what: "The server that actually owns the zone for platformvisualizer.dev.",
        receives: "A query for a record in its zone.",
        returns: "The configured record — here an A record.",
        why: "This is the source of truth. Everything above it only points here.",
        related: [
          { label: "DNS records", slug: "dns" },
          { label: "TTL", slug: "dns" },
        ],
      },
    },
    {
      id: "origin",
      label: "Origin server",
      subtitle: "76.76.21.21",
      x: 38,
      y: 78,
      kind: "server",
      inspector: {
        what: "The machine that will eventually serve the website.",
        receives: "A TCP connection to the resolved IP.",
        returns: "Application traffic — not a DNS answer.",
        why: "DNS only finds the door. The browser still has to knock.",
        related: [
          { label: "HTTPS", slug: "https" },
          { label: "Load balancer", slug: "load-balancer" },
        ],
      },
    },
  ],
  edges: [
    { id: "b-c", from: "browser", to: "cache", bidirectional: true },
    { id: "c-r", from: "cache", to: "resolver", bidirectional: true },
    { id: "r-root", from: "resolver", to: "root", bidirectional: true },
    { id: "r-tld", from: "resolver", to: "tld", bidirectional: true },
    { id: "r-auth", from: "resolver", to: "auth", bidirectional: true },
    { id: "b-o", from: "browser", to: "origin" },
  ],
  zones: [
    {
      id: "client-zone",
      label: "Your machine",
      x: 3,
      y: 6,
      width: 22,
      height: 56,
      kind: "host",
    },
    {
      id: "dns-zone",
      label: "DNS hierarchy",
      x: 56,
      y: 6,
      width: 41,
      height: 88,
      kind: "network",
    },
  ],
  initialStates: {
    browser: { status: "idle", question: "platformvisualizer.dev" },
    cache: { status: "cold", record: "miss" },
    resolver: { status: "idle" },
    root: { status: "idle" },
    tld: { status: "idle" },
    auth: { status: "idle" },
    origin: { visible: true, status: "waiting" },
  },
  steps: [
    {
      id: "type",
      title: "A name, not an address",
      explanation: "The browser does not know the server IP yet.",
      duration: 2200,
      events: [
        { type: "highlight", nodeIds: ["browser"] },
        { type: "state", nodeId: "browser", patch: { status: "needs IP" } },
        {
          type: "explain",
          text: "You typed a name. Packets cannot route to a name — they need an IP.",
        },
      ],
    },
    {
      id: "cache-check",
      title: "Check the local cache",
      explanation: "First stop: has this machine already asked this question?",
      duration: 2400,
      events: [
        { type: "highlight", nodeIds: ["browser", "cache"] },
        {
          type: "packet",
          from: "browser",
          to: "cache",
          label: "A? platformvisualizer.dev",
          kind: "query",
          duration: 800,
        },
        {
          type: "state",
          nodeId: "cache",
          patch: { status: "miss", record: "empty" },
          delay: 800,
        },
        {
          type: "explain",
          text: "Cache miss. The answer is not on this laptop.",
          delay: 850,
        },
        { type: "latency", nodeId: "cache", ms: 0.2, delay: 850 },
      ],
    },
    {
      id: "ask-resolver",
      title: "Ask the configured resolver",
      explanation: "It asks the configured DNS resolver.",
      duration: 2600,
      events: [
        { type: "highlight", nodeIds: ["cache", "resolver"] },
        {
          type: "packet",
          from: "cache",
          to: "resolver",
          label: "A? platformvisualizer.dev",
          kind: "query",
          duration: 1000,
        },
        {
          type: "state",
          nodeId: "resolver",
          patch: { status: "recursing", question: "A platformvisualizer.dev" },
          delay: 900,
        },
        {
          type: "explain",
          text: "1.1.1.1 now owns the question. The browser waits.",
          delay: 1000,
        },
        { type: "latency", nodeId: "resolver", ms: 12, delay: 1000 },
      ],
    },
    {
      id: "ask-root",
      title: "Start at the root",
      explanation: "The resolver asks the DNS hierarchy, beginning at the root.",
      duration: 2800,
      events: [
        { type: "highlight", nodeIds: ["resolver", "root"] },
        {
          type: "packet",
          from: "resolver",
          to: "root",
          label: "Where is .dev?",
          kind: "query",
          duration: 900,
        },
        {
          type: "state",
          nodeId: "root",
          patch: { status: "referral", answer: "ask .dev TLD" },
          delay: 900,
        },
        {
          type: "packet",
          from: "root",
          to: "resolver",
          label: "NS: a.nic.dev",
          kind: "response",
          delay: 1000,
          duration: 900,
        },
        {
          type: "explain",
          text: "Root does not know the site. It only knows who runs .dev.",
          delay: 1100,
        },
      ],
    },
    {
      id: "ask-tld",
      title: "Ask the TLD",
      explanation: "The .dev registry knows which nameservers own this zone.",
      duration: 2800,
      events: [
        { type: "highlight", nodeIds: ["resolver", "tld"] },
        {
          type: "packet",
          from: "resolver",
          to: "tld",
          label: "NS? platformvisualizer.dev",
          kind: "query",
          duration: 900,
        },
        {
          type: "state",
          nodeId: "tld",
          patch: { status: "referral", answer: "ns.cloudflare.com" },
          delay: 900,
        },
        {
          type: "packet",
          from: "tld",
          to: "resolver",
          label: "NS ns.cloudflare.com",
          kind: "response",
          delay: 1000,
          duration: 900,
        },
        {
          type: "explain",
          text: "Delegation again. The TLD points at the zone’s authoritative servers.",
          delay: 1100,
        },
      ],
    },
    {
      id: "ask-auth",
      title: "Ask the source of truth",
      explanation: "Only the authoritative server has the A record.",
      duration: 3000,
      events: [
        { type: "highlight", nodeIds: ["resolver", "auth"] },
        {
          type: "packet",
          from: "resolver",
          to: "auth",
          label: "A? platformvisualizer.dev",
          kind: "query",
          duration: 900,
        },
        {
          type: "state",
          nodeId: "auth",
          patch: { status: "answer", record: "76.76.21.21  TTL=300" },
          delay: 900,
        },
        {
          type: "packet",
          from: "auth",
          to: "resolver",
          label: "A 76.76.21.21",
          kind: "response",
          delay: 1050,
          duration: 950,
        },
        {
          type: "explain",
          text: "This is the actual mapping. Everything else was just finding this box.",
          delay: 1100,
        },
        { type: "latency", nodeId: "auth", ms: 18, delay: 1100 },
      ],
    },
    {
      id: "cache-return",
      title: "Cache and return",
      explanation: "The resolver caches the answer, then the laptop does too.",
      duration: 2800,
      events: [
        { type: "highlight", nodeIds: ["resolver", "cache", "browser"] },
        {
          type: "state",
          nodeId: "resolver",
          patch: { status: "cached", record: "76.76.21.21" },
        },
        {
          type: "packet",
          from: "resolver",
          to: "cache",
          label: "A 76.76.21.21",
          kind: "response",
          duration: 900,
        },
        {
          type: "state",
          nodeId: "cache",
          patch: { status: "hit next time", record: "76.76.21.21" },
          delay: 900,
        },
        {
          type: "packet",
          from: "cache",
          to: "browser",
          label: "76.76.21.21",
          kind: "response",
          delay: 1000,
          duration: 800,
        },
        {
          type: "state",
          nodeId: "browser",
          patch: { status: "has IP", record: "76.76.21.21" },
          delay: 1700,
        },
        {
          type: "explain",
          text: "Next visit can skip the hierarchy until the TTL expires.",
          delay: 1700,
        },
      ],
    },
    {
      id: "connect",
      title: "Now the browser can connect",
      explanation: "DNS is done. The browser finally knocks on the server.",
      duration: 2600,
      events: [
        { type: "highlight", nodeIds: ["browser", "origin"] },
        { type: "connection", edgeId: "b-o", open: true },
        {
          type: "packet",
          from: "browser",
          to: "origin",
          label: "TCP connect 76.76.21.21:443",
          kind: "syn",
          duration: 1100,
        },
        {
          type: "state",
          nodeId: "origin",
          patch: { status: "reached" },
          delay: 1100,
        },
        {
          type: "explain",
          text: "Name became a number. The rest of HTTPS can begin.",
          delay: 1200,
        },
      ],
    },
  ],
};
