import type { SimulationDefinition } from "@/lib/types";

export const dockerSimulation: SimulationDefinition = {
  id: "docker",
  nodes: [
    {
      id: "dockerfile",
      label: "Dockerfile",
      subtitle: "desired image recipe",
      x: 8,
      y: 20,
      kind: "control",
      inspector: {
        what: "A declarative recipe: base image, commands, files, default process.",
        receives: "Instructions from a developer.",
        returns: "A build plan the daemon can execute.",
        why: "The file is the source of truth for how a workload is packaged.",
        related: [
          { label: "Image layers", slug: "image-layers" },
          { label: "Image", slug: "image" },
        ],
      },
    },
    {
      id: "builder",
      label: "Builder",
      subtitle: "dockerd / buildkit",
      x: 32,
      y: 20,
      kind: "runtime",
      inspector: {
        what: "The engine that executes each instruction and snapshots a layer.",
        receives: "A Dockerfile and a build context.",
        returns: "An image made of stacked filesystem diffs.",
        why: "Unchanged instructions reuse cached layers. That is why order matters.",
        related: [
          { label: "Image layers", slug: "image-layers" },
          { label: "Container runtime", slug: "container-runtime" },
        ],
      },
    },
    {
      id: "layers",
      label: "Image layers",
      subtitle: "FROM → RUN → COPY",
      x: 32,
      y: 52,
      kind: "storage",
      inspector: {
        what: "Immutable filesystem diffs stacked into a single image.",
        receives: "The result of one instruction.",
        returns: "A content-addressed layer digest.",
        why: "Pulls and rebuilds only transfer what changed.",
        related: [
          { label: "Image", slug: "image" },
          { label: "Registry", slug: "registry" },
        ],
      },
    },
    {
      id: "image",
      label: "Image",
      subtitle: "app:1.4",
      x: 56,
      y: 20,
      kind: "storage",
      inspector: {
        what: "A frozen package: layers + config + default command.",
        receives: "A completed build or a pull.",
        returns: "A template the runtime can instantiate.",
        why: "Images are what you ship. Containers are what you run.",
        related: [
          { label: "Container", slug: "container" },
          { label: "Registry", slug: "registry" },
        ],
      },
    },
    {
      id: "registry",
      label: "Registry",
      subtitle: "ghcr / ECR / Docker Hub",
      x: 80,
      y: 20,
      kind: "storage",
      inspector: {
        what: "A content-addressed store for images.",
        receives: "A push of layers + a tag.",
        returns: "The same bytes to any host that pulls.",
        why: "Build once, run anywhere that can pull.",
        related: [
          { label: "Image", slug: "image" },
          { label: "OCI", slug: "image" },
        ],
      },
    },
    {
      id: "host",
      label: "Host kernel",
      subtitle: "shared with other containers",
      x: 56,
      y: 72,
      kind: "runtime",
      inspector: {
        what: "The machine’s Linux kernel. Containers do not boot their own.",
        receives: "System calls from the isolated process.",
        returns: "Files, sockets, CPU time — scoped by namespaces and cgroups.",
        why: "This is the real difference from a VM: one kernel, many isolated processes.",
        related: [
          { label: "Namespaces", slug: "namespaces" },
          { label: "cgroups", slug: "cgroups" },
          { label: "Container vs VM", slug: "container" },
        ],
      },
    },
    {
      id: "runtime",
      label: "Runtime",
      subtitle: "runc / containerd",
      x: 80,
      y: 52,
      kind: "runtime",
      inspector: {
        what: "Creates the namespaces, cgroups, and root filesystem, then execs PID 1.",
        receives: "An image + run spec.",
        returns: "A running container process.",
        why: "Docker is UX. The runtime is the isolation machinery.",
        related: [
          { label: "Namespaces", slug: "namespaces" },
          { label: "cgroups", slug: "cgroups" },
        ],
      },
    },
    {
      id: "container",
      label: "Container process",
      subtitle: "PID 1 inside the ns",
      x: 80,
      y: 80,
      kind: "process",
      inspector: {
        what: "A normal Linux process with a filtered view of the machine.",
        receives: "Its own PID namespace, mounts, network, and cgroup limits.",
        returns: "Application behavior — logs, ports, files.",
        why: "If you understand a process, you are most of the way to understanding a container.",
        related: [
          { label: "Processes", slug: "processes" },
          { label: "Ports", slug: "ports" },
        ],
      },
    },
    {
      id: "vm",
      label: "VM contrast",
      subtitle: "guest kernel + hardware virt",
      x: 8,
      y: 72,
      kind: "server",
      inspector: {
        what: "A virtual machine boots a full guest kernel on emulated or paravirtual hardware.",
        receives: "A disk image and hypervisor schedule.",
        returns: "Strong isolation, slower start, more RAM.",
        why: "Containers isolate processes. VMs isolate machines. Different threat model, different cost.",
        related: [
          { label: "Virtual machines", slug: "virtual-machines" },
          { label: "Container", slug: "container" },
        ],
      },
    },
  ],
  edges: [
    { id: "df-b", from: "dockerfile", to: "builder" },
    { id: "b-l", from: "builder", to: "layers" },
    { id: "l-i", from: "layers", to: "image" },
    { id: "i-reg", from: "image", to: "registry" },
    { id: "reg-rt", from: "registry", to: "runtime" },
    { id: "rt-c", from: "runtime", to: "container" },
    { id: "h-c", from: "host", to: "container", bidirectional: true },
    { id: "rt-h", from: "runtime", to: "host" },
  ],
  zones: [
    {
      id: "build",
      label: "Build",
      x: 2,
      y: 6,
      width: 44,
      height: 58,
      kind: "control",
    },
    {
      id: "run",
      label: "Run on a shared kernel",
      x: 50,
      y: 58,
      width: 48,
      height: 36,
      kind: "host",
    },
  ],
  initialStates: {
    dockerfile: { status: "FROM node:22" },
    builder: { status: "idle" },
    layers: { status: "empty", layers: "0" },
    image: { status: "none" },
    registry: { status: "waiting" },
    host: { status: "idle" },
    runtime: { status: "idle" },
    container: { status: "not started", visible: true },
    vm: { status: "boots a guest OS" },
  },
  steps: [
    {
      id: "recipe",
      title: "A recipe, not a machine",
      explanation: "The Dockerfile describes the image. Nothing is running yet.",
      duration: 2200,
      events: [
        { type: "highlight", nodeIds: ["dockerfile"] },
        {
          type: "state",
          nodeId: "dockerfile",
          patch: { status: "FROM  RUN  COPY  CMD" },
        },
      ],
    },
    {
      id: "from",
      title: "FROM — the first layer",
      explanation: "Build starts with a base filesystem. That is layer 0.",
      duration: 2400,
      events: [
        { type: "highlight", nodeIds: ["dockerfile", "builder", "layers"] },
        {
          type: "packet",
          from: "dockerfile",
          to: "builder",
          label: "FROM node:22-slim",
          kind: "control",
          duration: 800,
        },
        {
          type: "state",
          nodeId: "layers",
          patch: { status: "layer 0 cached", layers: "1" },
          delay: 900,
        },
      ],
    },
    {
      id: "run",
      title: "RUN — mutate and snapshot",
      explanation: "Each RUN starts a throwaway container, then commits a new layer.",
      duration: 2600,
      events: [
        { type: "highlight", nodeIds: ["builder", "layers"] },
        {
          type: "packet",
          from: "builder",
          to: "layers",
          label: "RUN npm ci",
          kind: "data",
          duration: 900,
        },
        {
          type: "state",
          nodeId: "layers",
          patch: { status: "deps layer", layers: "2" },
          delay: 950,
        },
        {
          type: "explain",
          text: "Change a late COPY and this layer stays cached.",
          delay: 1000,
        },
      ],
    },
    {
      id: "copy",
      title: "COPY — app files",
      explanation: "Application bytes become their own layer on top.",
      duration: 2200,
      events: [
        { type: "highlight", nodeIds: ["builder", "layers"] },
        {
          type: "packet",
          from: "builder",
          to: "layers",
          label: "COPY . /app",
          kind: "data",
          duration: 800,
        },
        {
          type: "state",
          nodeId: "layers",
          patch: { status: "app layer", layers: "3" },
          delay: 850,
        },
      ],
    },
    {
      id: "image",
      title: "Image exists",
      explanation: "Config + layers assemble into app:1.4. Still not a running process.",
      duration: 2200,
      events: [
        { type: "highlight", nodeIds: ["layers", "image"] },
        {
          type: "packet",
          from: "layers",
          to: "image",
          label: "commit app:1.4",
          kind: "control",
          duration: 800,
        },
        {
          type: "state",
          nodeId: "image",
          patch: { status: "sha256:9f3a…  CMD node" },
          delay: 850,
        },
      ],
    },
    {
      id: "push",
      title: "Push to a registry",
      explanation: "Only new layer blobs are uploaded. Tags are pointers.",
      duration: 2400,
      events: [
        { type: "highlight", nodeIds: ["image", "registry"] },
        {
          type: "packet",
          from: "image",
          to: "registry",
          label: "push layers + tag",
          kind: "data",
          duration: 1000,
        },
        {
          type: "state",
          nodeId: "registry",
          patch: { status: "app:1.4 available" },
          delay: 1050,
        },
      ],
    },
    {
      id: "pull",
      title: "Another host pulls",
      explanation: "A runtime fetches the image so it can create a container.",
      duration: 2400,
      events: [
        { type: "highlight", nodeIds: ["registry", "runtime"] },
        {
          type: "packet",
          from: "registry",
          to: "runtime",
          label: "pull app:1.4",
          kind: "data",
          duration: 1000,
        },
        {
          type: "state",
          nodeId: "runtime",
          patch: { status: "image unpacked" },
          delay: 1050,
        },
      ],
    },
    {
      id: "isolate",
      title: "Namespaces + cgroups",
      explanation: "The runtime builds a box: PID, mount, net, user — then CPU/RAM limits.",
      duration: 2800,
      events: [
        { type: "highlight", nodeIds: ["runtime", "host"] },
        {
          type: "packet",
          from: "runtime",
          to: "host",
          label: "clone ns  +  cgroup",
          kind: "control",
          duration: 1000,
        },
        {
          type: "state",
          nodeId: "host",
          patch: { status: "ns + cgroup ready" },
          delay: 1050,
        },
        {
          type: "state",
          nodeId: "vm",
          patch: { status: "would boot a kernel here" },
          delay: 1100,
        },
        {
          type: "explain",
          text: "No guest OS. Isolation is a filtered view of this kernel.",
          delay: 1100,
        },
      ],
    },
    {
      id: "start",
      title: "Process starts",
      explanation: "PID 1 inside the container is just node — a process, not a tiny VM.",
      duration: 2800,
      events: [
        { type: "highlight", nodeIds: ["runtime", "container", "host"] },
        {
          type: "packet",
          from: "runtime",
          to: "container",
          label: "exec CMD node server.js",
          kind: "control",
          duration: 900,
        },
        {
          type: "state",
          nodeId: "container",
          patch: { status: "running  :3000", pid: "1 in ns / 18422 on host" },
          delay: 950,
        },
        { type: "connection", edgeId: "h-c", open: true, delay: 950 },
        {
          type: "explain",
          text: "Same kernel. Different namespaces. That is a container.",
          delay: 1000,
        },
      ],
    },
  ],
};
