import type { SimulationDefinition } from "@/lib/types";

export const gpuInferenceSimulation: SimulationDefinition = {
  id: "gpu-inference",
  nodes: [
    {
      id: "users",
      label: "Prompts",
      subtitle: "concurrent users",
      x: 8,
      y: 22,
      kind: "client",
      inspector: {
        what: "Independent generation requests. Each is a sequence of tokens, not one big job.",
        receives: "A user prompt.",
        returns: "A stream of completion tokens.",
        why: "Load is bursty. The serving stack exists to share one expensive GPU across many of these.",
        related: [
          { label: "Tokens", slug: "tokens" },
          { label: "Inference", slug: "inference" },
        ],
      },
    },
    {
      id: "gateway",
      label: "AI gateway",
      subtitle: "auth + routing",
      x: 30,
      y: 22,
      kind: "gateway",
      inspector: {
        what: "The front door: authenticate, rate-limit, pick a model endpoint.",
        receives: "HTTP inference requests.",
        returns: "A routed request to a scheduler or engine.",
        why: "Applications should not address raw GPU nodes.",
        related: [
          { label: "Model gateway", slug: "model-gateway" },
          { label: "Model endpoint", slug: "model-endpoint" },
        ],
      },
    },
    {
      id: "queue",
      label: "Scheduler / queue",
      subtitle: "waiting batch",
      x: 52,
      y: 22,
      kind: "queue",
      inspector: {
        what: "Holds inbound sequences until the engine can form an efficient batch.",
        receives: "Admitted requests.",
        returns: "A batch of sequences that fit in VRAM.",
        why: "A GPU hates running one short prompt at a time. Waiting a few ms often raises tokens/sec.",
        related: [
          { label: "Batching", slug: "batching" },
          { label: "Continuous batching", slug: "continuous-batching" },
        ],
      },
    },
    {
      id: "vllm",
      label: "vLLM",
      subtitle: "inference engine",
      x: 74,
      y: 22,
      kind: "runtime",
      inspector: {
        what: "A high-throughput serving engine: paged KV cache, continuous batching, streaming.",
        receives: "Tokenized sequences.",
        returns: "Next-token distributions, streamed back.",
        why: "The GPU kernel is the muscle. vLLM is how we keep it fed without wasting memory.",
        related: [
          { label: "KV cache", slug: "kv-cache" },
          { label: "vLLM", slug: "vllm" },
        ],
      },
    },
    {
      id: "gpu",
      label: "GPU",
      subtitle: "parallel cores",
      x: 74,
      y: 56,
      kind: "gpu",
      inspector: {
        what: "Thousands of cores executing the same matmuls across a batch.",
        receives: "A batch of tokens + weights in VRAM.",
        returns: "Logits for the next token of each sequence.",
        why: "Utilization collapses if the batch is tiny or memory-bound.",
        related: [
          { label: "CUDA", slug: "cuda" },
          { label: "Utilization", slug: "utilization" },
        ],
      },
    },
    {
      id: "vram",
      label: "VRAM",
      subtitle: "weights + KV cache",
      x: 52,
      y: 56,
      kind: "storage",
      inspector: {
        what: "On-device memory. Weights stay resident. KV cache grows with every generated token.",
        receives: "Model load, then per-token cache writes.",
        returns: "Fast access for attention — until you run out.",
        why: "At high concurrency the cache, not compute, is usually the wall.",
        related: [
          { label: "KV cache", slug: "kv-cache" },
          { label: "Memory pressure", slug: "memory-pressure" },
        ],
      },
    },
    {
      id: "stream",
      label: "Token stream",
      subtitle: "tokens / sec",
      x: 30,
      y: 56,
      kind: "process",
      inspector: {
        what: "Decoded tokens leaving the engine toward each client.",
        receives: "Sampled token IDs.",
        returns: "Server-sent chunks the UI can append.",
        why: "Users feel time-to-first-token. Throughput is a fleet metric. They are not the same.",
        related: [
          { label: "Latency", slug: "latency" },
          { label: "Tokens/sec", slug: "tokens-sec" },
        ],
      },
    },
    {
      id: "bottleneck",
      label: "Bottleneck",
      subtitle: "what saturates first",
      x: 8,
      y: 56,
      kind: "control",
      inspector: {
        what: "A live diagnosis of the scarce resource at the current load.",
        receives: "Queue depth, GPU util, VRAM, tokens/sec.",
        returns: "The constraint you would scale next.",
        why: "10, 100, and 1000 users fail for different reasons.",
        related: [
          { label: "Autoscaling", slug: "autoscaling" },
          { label: "Throughput", slug: "throughput" },
        ],
      },
    },
  ],
  edges: [
    { id: "u-g", from: "users", to: "gateway" },
    { id: "g-q", from: "gateway", to: "queue" },
    { id: "q-v", from: "queue", to: "vllm" },
    { id: "v-gpu", from: "vllm", to: "gpu" },
    { id: "gpu-vram", from: "gpu", to: "vram", bidirectional: true },
    { id: "gpu-s", from: "gpu", to: "stream" },
    { id: "s-u", from: "stream", to: "users" },
  ],
  zones: [
    {
      id: "serve",
      label: "Serving path",
      x: 22,
      y: 8,
      width: 66,
      height: 30,
      kind: "public",
    },
    {
      id: "device",
      label: "Device",
      x: 44,
      y: 42,
      width: 44,
      height: 36,
      kind: "vram",
    },
  ],
  initialStates: {
    users: { status: "10 prompts", load: 10 },
    gateway: { status: "idle" },
    queue: { status: "depth 0" },
    vllm: { status: "warm" },
    gpu: { status: "22% util", util: 22 },
    vram: { status: "weights 14GB  KV 1GB" },
    stream: { status: "0 tok/s" },
    bottleneck: { status: "headroom" },
  },
  selectControls: [
    {
      id: "load",
      label: "Concurrent requests",
      defaultValue: "10",
      options: [
        { label: "10 users", value: "10" },
        { label: "100 users", value: "100" },
        { label: "1000 users", value: "1000" },
      ],
    },
  ],
  controlEffects: {
    load: {
      "10": {
        caption: "10 users: the GPU has slack. Latency is dominated by model compute, not the queue.",
        states: {
          users: { status: "10 prompts", load: 10 },
          queue: { status: "depth 0" },
          gpu: { status: "22% util", util: 22 },
          vram: { status: "weights 14GB  KV 1GB" },
          stream: { status: "180 tok/s" },
          bottleneck: { status: "none — headroom" },
        },
      },
      "100": {
        caption: "100 users: continuous batching fills the GPU. KV cache is growing.",
        states: {
          users: { status: "100 prompts", load: 100 },
          queue: { status: "depth 12" },
          gpu: { status: "78% util", util: 78 },
          vram: { status: "weights 14GB  KV 18GB" },
          stream: { status: "2400 tok/s" },
          bottleneck: { status: "batching / scheduler" },
        },
      },
      "1000": {
        caption: "1000 users: VRAM for the KV cache is the wall. New requests queue. Tokens/sec flattens.",
        states: {
          users: { status: "1000 prompts", load: 1000 },
          queue: { status: "depth 640" },
          gpu: { status: "99% util", util: 99 },
          vram: { status: "weights 14GB  KV FULL" },
          stream: { status: "3100 tok/s  (capped)" },
          bottleneck: { status: "KV cache / GPU memory" },
        },
      },
    },
  },
  steps: [
    {
      id: "arrive",
      title: "Prompts arrive",
      explanation: "Many users submit at once. None of them talk to the GPU directly.",
      duration: 2300,
      events: [
        { type: "highlight", nodeIds: ["users", "gateway"] },
        {
          type: "packet",
          from: "users",
          to: "gateway",
          label: "POST /v1/chat",
          kind: "prompt",
          duration: 800,
        },
        {
          type: "packet",
          from: "users",
          to: "gateway",
          label: "Explain Kubernetes",
          kind: "prompt",
          delay: 180,
          duration: 800,
        },
        {
          type: "state",
          nodeId: "gateway",
          patch: { status: "admitting" },
          delay: 850,
        },
      ],
    },
    {
      id: "admit",
      title: "Gateway routes",
      explanation: "Auth, model name, and limits are decided before a kernel ever runs.",
      duration: 2300,
      events: [
        { type: "highlight", nodeIds: ["gateway", "queue"] },
        {
          type: "packet",
          from: "gateway",
          to: "queue",
          label: "route llama-70b",
          kind: "control",
          duration: 800,
        },
        {
          type: "state",
          nodeId: "queue",
          patch: { status: "waiting for batch" },
          delay: 850,
        },
      ],
    },
    {
      id: "batch",
      title: "Dynamic batch",
      explanation: "vLLM groups sequences that can share one forward pass.",
      duration: 2500,
      events: [
        { type: "highlight", nodeIds: ["queue", "vllm"] },
        {
          type: "packet",
          from: "queue",
          to: "vllm",
          label: "batch 10 sequences",
          kind: "data",
          duration: 900,
        },
        {
          type: "state",
          nodeId: "vllm",
          patch: { status: "continuous batch" },
          delay: 950,
        },
        {
          type: "explain",
          text: "New requests can join a batch mid-generation. That is continuous batching.",
          delay: 1000,
        },
      ],
    },
    {
      id: "load-weights",
      title: "Weights already in VRAM",
      explanation: "The model is resident. We are not loading 70B parameters per request.",
      duration: 2400,
      events: [
        { type: "highlight", nodeIds: ["vllm", "vram", "gpu"] },
        {
          type: "packet",
          from: "vllm",
          to: "gpu",
          label: "forward pass",
          kind: "data",
          duration: 900,
        },
        {
          type: "state",
          nodeId: "vram",
          patch: { status: "weights hot" },
          delay: 950,
        },
        {
          type: "state",
          nodeId: "gpu",
          patch: { status: "compute" },
          delay: 950,
        },
      ],
    },
    {
      id: "kv",
      title: "KV cache grows",
      explanation: "Each new token writes keys and values so attention does not recompute history.",
      duration: 2600,
      events: [
        { type: "highlight", nodeIds: ["gpu", "vram"] },
        {
          type: "packet",
          from: "gpu",
          to: "vram",
          label: "write KV page",
          kind: "data",
          duration: 800,
        },
        {
          type: "state",
          nodeId: "vram",
          patch: { status: "KV pages allocated" },
          delay: 850,
        },
        {
          type: "explain",
          text: "Long contexts and many users compete for the same HBM.",
          delay: 900,
        },
      ],
    },
    {
      id: "decode",
      title: "Next token, then the next",
      explanation: "Generation is a loop: one token, append, repeat — streamed outward.",
      duration: 2800,
      events: [
        { type: "highlight", nodeIds: ["gpu", "stream", "users"] },
        {
          type: "packet",
          from: "gpu",
          to: "stream",
          label: "token: Kubernetes",
          kind: "token",
          duration: 700,
        },
        {
          type: "packet",
          from: "stream",
          to: "users",
          label: "chunk",
          kind: "token",
          delay: 750,
          duration: 800,
        },
        {
          type: "state",
          nodeId: "stream",
          patch: { status: "streaming" },
          delay: 800,
        },
      ],
    },
    {
      id: "scale",
      title: "Raise the load",
      explanation: "Use the control: 10 → 100 → 1000. Watch which box saturates.",
      duration: 3200,
      events: [
        { type: "highlight", nodeIds: ["users", "queue", "gpu", "vram", "bottleneck"] },
        {
          type: "explain",
          text: "10 is compute-bound slack. 100 fills the batcher. 1000 hits KV memory.",
        },
        {
          type: "state",
          nodeId: "bottleneck",
          patch: { status: "toggle load to see the wall" },
        },
      ],
    },
  ],
};
