import type { SimulationDefinition } from "@/lib/types";

export const httpsSimulation: SimulationDefinition = {
  id: "https",
  nodes: [
    {
      id: "browser",
      label: "Browser",
      subtitle: "https://platformvisualizer.dev",
      x: 8,
      y: 22,
      kind: "client",
      inspector: {
        what: "A client that wants a trusted, encrypted HTTP conversation.",
        receives: "A URL.",
        returns: "Rendered HTML once the full stack succeeds.",
        why: "Humans start here. Every hop below exists so this box can paint pixels.",
        related: [
          { label: "DNS", slug: "dns" },
          { label: "TLS", slug: "tls" },
          { label: "HTTP", slug: "http" },
        ],
      },
    },
    {
      id: "dns",
      label: "DNS",
      subtitle: "name → IP",
      x: 8,
      y: 62,
      kind: "dns",
      inspector: {
        what: "Resolves the hostname before any packet can be routed.",
        receives: "platformvisualizer.dev",
        returns: "76.76.21.21",
        why: "TCP needs a destination address, not a brand name.",
        related: [{ label: "DNS resolution", slug: "dns" }],
      },
    },
    {
      id: "router",
      label: "Default gateway",
      subtitle: "home / office router",
      x: 32,
      y: 22,
      kind: "router",
      inspector: {
        what: "The first hop off your subnet. It rewrites or forwards toward the internet.",
        receives: "A packet destined off-LAN.",
        returns: "The same packet, one hop closer.",
        why: "Your laptop does not have a full map of the internet — only a default route.",
        related: [
          { label: "Gateway", slug: "gateway" },
          { label: "NAT", slug: "nat" },
          { label: "Route table", slug: "route-table" },
        ],
      },
    },
    {
      id: "internet",
      label: "Internet",
      subtitle: "many autonomous systems",
      x: 32,
      y: 62,
      kind: "network",
      inspector: {
        what: "A mesh of independently operated networks that agree to forward IP.",
        receives: "A packet with a destination IP.",
        returns: "The packet at a peering edge near the destination.",
        why: "No single company owns the path. BGP glues the path together.",
        related: [
          { label: "Router", slug: "router" },
          { label: "IP address", slug: "ip-address" },
        ],
      },
    },
    {
      id: "lb",
      label: "Load balancer",
      subtitle: "edge :443",
      x: 58,
      y: 22,
      kind: "gateway",
      inspector: {
        what: "The public front door. It terminates or forwards client connections.",
        receives: "Inbound TCP/TLS from the internet.",
        returns: "A chosen healthy backend.",
        why: "Browsers hit one stable name. Capacity hides behind it.",
        related: [
          { label: "Reverse proxy", slug: "reverse-proxy" },
          { label: "TLS", slug: "tls" },
        ],
      },
    },
    {
      id: "server",
      label: "Application server",
      subtitle: "private origin",
      x: 82,
      y: 22,
      kind: "server",
      inspector: {
        what: "The process that understands the HTTP request and builds a response.",
        receives: "GET / after TLS is established.",
        returns: "HTTP 200 and a body.",
        why: "This is the workload. Everything else is how we reach it safely.",
        related: [
          { label: "HTTPS", slug: "https" },
          { label: "Reverse proxy", slug: "reverse-proxy" },
        ],
      },
    },
    {
      id: "page",
      label: "Rendered page",
      subtitle: "document + assets",
      x: 82,
      y: 62,
      kind: "client",
      inspector: {
        what: "The visible result of a successful request.",
        receives: "An HTTP response body.",
        returns: "Pixels, and usually more requests for CSS/JS.",
        why: "The user only sees this. The path above is why it appeared.",
        related: [{ label: "HTTP", slug: "http" }, { label: "CDN", slug: "cdn" }],
      },
    },
  ],
  edges: [
    { id: "b-dns", from: "browser", to: "dns", bidirectional: true },
    { id: "b-r", from: "browser", to: "router" },
    { id: "r-i", from: "router", to: "internet" },
    { id: "i-lb", from: "internet", to: "lb" },
    { id: "lb-s", from: "lb", to: "server", bidirectional: true },
    { id: "s-p", from: "server", to: "page" },
    { id: "b-lb", from: "browser", to: "lb", bidirectional: true },
  ],
  zones: [
    {
      id: "local",
      label: "Local network",
      x: 2,
      y: 8,
      width: 42,
      height: 72,
      kind: "private",
    },
    {
      id: "edge",
      label: "Provider edge",
      x: 50,
      y: 8,
      width: 48,
      height: 72,
      kind: "public",
    },
  ],
  initialStates: {
    browser: { status: "navigating" },
    dns: { status: "idle" },
    router: { status: "idle" },
    internet: { status: "idle" },
    lb: { status: "listening :443" },
    server: { status: "idle" },
    page: { status: "blank", visible: true },
  },
  steps: [
    {
      id: "url",
      title: "Open the URL",
      explanation: "The browser parses https://platformvisualizer.dev — scheme, host, path.",
      duration: 2200,
      events: [
        { type: "highlight", nodeIds: ["browser"] },
        { type: "state", nodeId: "browser", patch: { status: "needs IP + TLS" } },
      ],
    },
    {
      id: "dns",
      title: "Resolve the name",
      explanation: "DNS returns 76.76.21.21. Routing can begin.",
      duration: 2600,
      events: [
        { type: "highlight", nodeIds: ["browser", "dns"] },
        {
          type: "packet",
          from: "browser",
          to: "dns",
          label: "A? platformvisualizer.dev",
          kind: "query",
          duration: 800,
        },
        {
          type: "packet",
          from: "dns",
          to: "browser",
          label: "76.76.21.21",
          kind: "response",
          delay: 900,
          duration: 800,
        },
        {
          type: "state",
          nodeId: "browser",
          patch: { status: "dest 76.76.21.21:443" },
          delay: 1600,
        },
        { type: "latency", nodeId: "dns", ms: 18, delay: 1600 },
      ],
    },
    {
      id: "route",
      title: "Leave the subnet",
      explanation: "The OS looks up the route table. Off-LAN traffic goes to the gateway.",
      duration: 2400,
      events: [
        { type: "highlight", nodeIds: ["browser", "router", "internet"] },
        {
          type: "packet",
          from: "browser",
          to: "router",
          label: "dst 76.76.21.21",
          kind: "data",
          duration: 700,
        },
        {
          type: "packet",
          from: "router",
          to: "internet",
          label: "NAT + forward",
          kind: "data",
          delay: 750,
          duration: 800,
        },
        {
          type: "state",
          nodeId: "router",
          patch: { status: "MASQUERADE" },
          delay: 750,
        },
      ],
    },
    {
      id: "syn",
      title: "TCP SYN",
      explanation: "The client asks to open a reliable session: SYN.",
      duration: 2000,
      events: [
        { type: "highlight", nodeIds: ["internet", "lb"] },
        { type: "connection", edgeId: "b-lb", open: true },
        {
          type: "packet",
          from: "internet",
          to: "lb",
          label: "SYN seq=0",
          kind: "syn",
          duration: 900,
        },
        { type: "state", nodeId: "lb", patch: { tcp: "SYN_RECV" }, delay: 900 },
      ],
    },
    {
      id: "synack",
      title: "TCP SYN-ACK",
      explanation: "The load balancer agrees: SYN-ACK.",
      duration: 2000,
      events: [
        { type: "highlight", nodeIds: ["lb", "browser"] },
        {
          type: "packet",
          from: "lb",
          to: "internet",
          label: "SYN-ACK seq=0 ack=1",
          kind: "ack",
          duration: 900,
        },
        { type: "state", nodeId: "browser", patch: { tcp: "ESTABLISHING" }, delay: 900 },
      ],
    },
    {
      id: "ack",
      title: "TCP ACK",
      explanation: "The handshake completes. Bytes can now flow in order.",
      duration: 2000,
      events: [
        { type: "highlight", nodeIds: ["browser", "lb"] },
        {
          type: "packet",
          from: "internet",
          to: "lb",
          label: "ACK",
          kind: "ack",
          duration: 800,
        },
        {
          type: "state",
          nodeId: "lb",
          patch: { tcp: "ESTABLISHED", tls: "pending" },
          delay: 800,
        },
        {
          type: "explain",
          text: "TCP is a pipe. It is not yet private or authenticated.",
          delay: 850,
        },
      ],
    },
    {
      id: "clienthello",
      title: "TLS ClientHello",
      explanation: "The browser offers cipher suites and the SNI hostname.",
      duration: 2400,
      events: [
        { type: "highlight", nodeIds: ["browser", "lb"] },
        {
          type: "packet",
          from: "internet",
          to: "lb",
          label: "ClientHello  SNI=platformvisualizer.dev",
          kind: "tls",
          duration: 1000,
        },
        {
          type: "state",
          nodeId: "lb",
          patch: { tls: "negotiating" },
          delay: 1000,
        },
      ],
    },
    {
      id: "serverhello",
      title: "TLS ServerHello + certificate",
      explanation: "The edge proves it owns the name and agrees on keys.",
      duration: 2800,
      events: [
        { type: "highlight", nodeIds: ["lb", "browser"] },
        {
          type: "packet",
          from: "lb",
          to: "internet",
          label: "ServerHello + cert",
          kind: "tls",
          duration: 1000,
        },
        {
          type: "state",
          nodeId: "browser",
          patch: { tls: "verifying cert" },
          delay: 1000,
        },
        {
          type: "explain",
          text: "The certificate chain is why the lock icon can appear.",
          delay: 1100,
        },
        { type: "latency", nodeId: "lb", ms: 42, delay: 1100 },
      ],
    },
    {
      id: "finished",
      title: "TLS keys installed",
      explanation: "Finished messages seal the handshake. Application data can be encrypted.",
      duration: 2200,
      events: [
        { type: "highlight", nodeIds: ["browser", "lb"] },
        {
          type: "packet",
          from: "internet",
          to: "lb",
          label: "Finished",
          kind: "tls",
          duration: 800,
        },
        {
          type: "state",
          nodeId: "lb",
          patch: { tls: "1.3 open" },
          delay: 800,
        },
        {
          type: "state",
          nodeId: "browser",
          patch: { tls: "1.3 open" },
          delay: 800,
        },
      ],
    },
    {
      id: "get",
      title: "HTTP GET",
      explanation: "Only now does the actual request travel — encrypted on the wire.",
      duration: 2600,
      events: [
        { type: "highlight", nodeIds: ["lb", "server"] },
        {
          type: "packet",
          from: "lb",
          to: "server",
          label: "GET /  Host: platformvisualizer.dev",
          kind: "http",
          duration: 900,
        },
        {
          type: "state",
          nodeId: "server",
          patch: { status: "handling GET /" },
          delay: 900,
        },
        { type: "connection", edgeId: "lb-s", open: true },
      ],
    },
    {
      id: "response",
      title: "HTTP response",
      explanation: "The origin returns 200. The browser can paint.",
      duration: 2800,
      events: [
        { type: "highlight", nodeIds: ["server", "page", "browser"] },
        {
          type: "packet",
          from: "server",
          to: "lb",
          label: "200 OK  text/html",
          kind: "http",
          duration: 800,
        },
        {
          type: "packet",
          from: "lb",
          to: "internet",
          label: "encrypted 200",
          kind: "http",
          delay: 850,
          duration: 800,
        },
        {
          type: "state",
          nodeId: "page",
          patch: { status: "document ready" },
          delay: 1600,
        },
        {
          type: "state",
          nodeId: "browser",
          patch: { status: "rendered" },
          delay: 1600,
        },
        {
          type: "explain",
          text: "DNS found it. TCP connected. TLS trusted it. HTTP fetched it.",
          delay: 1650,
        },
      ],
    },
  ],
};
