import type { SimulationDefinition } from "@/lib/types";

export const inferenceSimulation: SimulationDefinition = {
  id: "inference",
  nodes: [
    {
      id: "prompt",
      label: "Prompt",
      subtitle: "Explain Kubernetes",
      x: 10,
      y: 28,
      kind: "client",
      inspector: {
        what: "Human text. The model will never see these characters as characters.",
        receives: "A string.",
        returns: "A trip through the tokenizer.",
        why: "Cost and context are counted after this box, in tokens.",
        related: [{ label: "Tokens", slug: "tokens" }, { label: "Tokenizer", slug: "tokenizer" }],
      },
    },
    {
      id: "tok",
      label: "Tokenizer",
      subtitle: "text → ids",
      x: 32,
      y: 28,
      kind: "runtime",
      inspector: {
        what: "Cuts text into the discrete pieces the model was trained on.",
        receives: "A string.",
        returns: "A list of token ids.",
        why: "“Kubernetes” might be two tokens. Billing does not care about words.",
        related: [{ label: "Tokenizer", slug: "tokenizer" }, { label: "Tokens", slug: "tokens" }],
      },
    },
    {
      id: "emb",
      label: "Embeddings",
      subtitle: "ids → vectors",
      x: 54,
      y: 28,
      kind: "storage",
      inspector: {
        what: "A lookup table: each token id becomes a vector.",
        receives: "Token ids.",
        returns: "A sequence of embeddings.",
        why: "The model does math on coordinates, not on spelling.",
        related: [{ label: "Embeddings", slug: "embeddings" }, { label: "Parameters", slug: "parameters" }],
      },
    },
    {
      id: "xf",
      label: "Transformer",
      subtitle: "the model",
      x: 76,
      y: 28,
      kind: "gpu",
      inspector: {
        what: "Blocks that let every token look at the others, then update.",
        receives: "Embeddings (+ positions).",
        returns: "A vector for “what comes next.”",
        why: "You do not need the paper to operate this — you need this picture.",
        related: [
          { label: "Transformer (high level)", slug: "transformer" },
          { label: "Weights", slug: "weights" },
        ],
      },
    },
    {
      id: "probs",
      label: "Next-token probs",
      subtitle: "a distribution",
      x: 76,
      y: 62,
      kind: "control",
      inspector: {
        what: "A score for every token in the vocab. Sampling picks one.",
        receives: "Logits from the last layer.",
        returns: "One token id.",
        why: "Generation is a loop of this choice — not one big answer.",
        related: [{ label: "Inference", slug: "inference" }],
      },
    },
    {
      id: "out",
      label: "Token",
      subtitle: "“Kubernetes”",
      x: 54,
      y: 62,
      kind: "process",
      inspector: {
        what: "The chosen piece, decoded back to text.",
        receives: "A token id.",
        returns: "A chunk on the stream.",
        why: "Time-to-first-token is “how long until this box first fires.”",
        related: [{ label: "Tokens", slug: "tokens" }, { label: "Latency", slug: "latency" }],
      },
    },
    {
      id: "stream",
      label: "Stream",
      subtitle: "append + repeat",
      x: 32,
      y: 62,
      kind: "queue",
      inspector: {
        what: "The growing string the user sees.",
        receives: "Each decoded token.",
        returns: "A longer completion. Then the loop uses it as new context.",
        why: "The next step feeds this back in. That is autoregression.",
        related: [
          { label: "Context window", slug: "context-window" },
          { label: "Inference", slug: "inference" },
        ],
      },
    },
  ],
  edges: [
    { id: "p-t", from: "prompt", to: "tok" },
    { id: "t-e", from: "tok", to: "emb" },
    { id: "e-x", from: "emb", to: "xf" },
    { id: "x-pr", from: "xf", to: "probs" },
    { id: "pr-o", from: "probs", to: "out" },
    { id: "o-s", from: "out", to: "stream" },
    { id: "s-x", from: "stream", to: "xf" },
  ],
  zones: [
    { id: "loop", label: "Then again, for the next token", x: 24, y: 48, width: 64, height: 28, kind: "vram" },
  ],
  initialStates: {
    prompt: { status: "Explain Kubernetes" },
    tok: { status: "idle" },
    emb: { status: "idle" },
    xf: { status: "weights loaded" },
    probs: { status: "—" },
    out: { status: "—" },
    stream: { status: "" },
  },
  steps: [
    {
      id: "ask",
      title: "A prompt",
      explanation: "Words in. The model does not read English — it reads ids.",
      duration: 2200,
      events: [{ type: "highlight", nodeIds: ["prompt"] }],
    },
    {
      id: "tok",
      title: "Tokenizer",
      explanation: "Explain · Kubernetes · … become a short list of ids.",
      duration: 2400,
      events: [
        { type: "highlight", nodeIds: ["prompt", "tok"] },
        {
          type: "packet",
          from: "prompt",
          to: "tok",
          label: "Explain Kubernetes",
          kind: "prompt",
          duration: 800,
        },
        { type: "state", nodeId: "tok", patch: { status: "[1012, 88, 4401]" }, delay: 850 },
      ],
    },
    {
      id: "emb",
      title: "Embeddings",
      explanation: "Each id becomes a vector. Spelling is gone. Position is added.",
      duration: 2300,
      events: [
        { type: "highlight", nodeIds: ["tok", "emb"] },
        {
          type: "packet",
          from: "tok",
          to: "emb",
          label: "ids → vectors",
          kind: "data",
          duration: 800,
        },
        { type: "state", nodeId: "emb", patch: { status: "seq length 3" }, delay: 850 },
      ],
    },
    {
      id: "xf",
      title: "Transformer",
      explanation: "Every token can look at the others. One forward pass. No training.",
      duration: 2500,
      events: [
        { type: "highlight", nodeIds: ["emb", "xf"] },
        {
          type: "packet",
          from: "emb",
          to: "xf",
          label: "forward",
          kind: "data",
          duration: 900,
        },
        { type: "state", nodeId: "xf", patch: { status: "inference" }, delay: 950 },
        {
          type: "explain",
          text: "Training would update weights. Inference only uses them.",
          delay: 1000,
        },
      ],
    },
    {
      id: "probs",
      title: "A distribution",
      explanation: "Not “the answer.” A pile of likely next pieces. Sampling picks one.",
      duration: 2400,
      events: [
        { type: "highlight", nodeIds: ["xf", "probs"] },
        {
          type: "packet",
          from: "xf",
          to: "probs",
          label: "logits",
          kind: "control",
          duration: 800,
        },
        { type: "state", nodeId: "probs", patch: { status: "is 0.18  a 0.09  …" }, delay: 850 },
      ],
    },
    {
      id: "token",
      title: "One token out",
      explanation: "The first visible piece. Time-to-first-token ends here.",
      duration: 2300,
      events: [
        { type: "highlight", nodeIds: ["probs", "out"] },
        {
          type: "packet",
          from: "probs",
          to: "out",
          label: "sample → “Kubernetes”",
          kind: "token",
          duration: 800,
        },
        { type: "state", nodeId: "out", patch: { status: "emitted" }, delay: 850 },
      ],
    },
    {
      id: "loop",
      title: "Append, then again",
      explanation: "The token joins the context. The next forward pass starts. That is the stream.",
      duration: 2800,
      events: [
        { type: "highlight", nodeIds: ["out", "stream", "xf"] },
        {
          type: "packet",
          from: "out",
          to: "stream",
          label: "chunk",
          kind: "token",
          duration: 700,
        },
        { type: "state", nodeId: "stream", patch: { status: "Kubernetes is…" }, delay: 750 },
        {
          type: "packet",
          from: "stream",
          to: "xf",
          label: "context + 1",
          kind: "data",
          delay: 900,
          duration: 800,
        },
        {
          type: "explain",
          text: "A reply is a loop of next-token. The GPU is rented for that loop.",
          delay: 1000,
        },
      ],
    },
  ],
};
