import type { SimulationDefinition } from "@/lib/types";

export const kubernetesSimulation: SimulationDefinition = {
  id: "kubernetes",
  nodes: [
    {
      id: "kubectl",
      label: "kubectl",
      subtitle: "replicas: 3",
      x: 8,
      y: 16,
      kind: "client",
      inspector: {
        what: "A client that sends desired state to the API server.",
        receives: "A manifest from a human or a GitOps controller.",
        returns: "An accepted object, not running containers.",
        why: "You declare what should exist. You do not SSH and start processes.",
        related: [
          { label: "API server", slug: "api-server" },
          { label: "Deployment", slug: "deployment" },
        ],
      },
    },
    {
      id: "apiserver",
      label: "API server",
      subtitle: "kube-apiserver",
      x: 32,
      y: 16,
      kind: "gateway",
      inspector: {
        what: "The only front door to cluster state. Authn, authz, validation live here.",
        receives: "REST/gRPC object mutations.",
        returns: "Admitted objects persisted to etcd.",
        why: "Controllers never talk to nodes directly. They watch this API.",
        related: [
          { label: "RBAC", slug: "rbac" },
          { label: "etcd", slug: "etcd" },
        ],
      },
    },
    {
      id: "etcd",
      label: "etcd",
      subtitle: "desired + actual objects",
      x: 56,
      y: 16,
      kind: "storage",
      inspector: {
        what: "The cluster’s consistent key-value store.",
        receives: "Serialized Kubernetes objects.",
        returns: "The last written truth.",
        why: "If it is not in etcd, the cluster does not believe it exists.",
        related: [
          { label: "Control plane", slug: "control-plane" },
          { label: "Consensus basics", slug: "consensus-basics" },
        ],
      },
    },
    {
      id: "controller",
      label: "Controller manager",
      subtitle: "reconciliation loop",
      x: 32,
      y: 46,
      kind: "control",
      inspector: {
        what: "A set of loops that compare desired vs observed and emit diffs.",
        receives: "Watch events from the API.",
        returns: "New objects (Pods) or patches when reality drifts.",
        why: "This is Kubernetes: continuously repair toward the spec.",
        related: [
          { label: "ReplicaSet", slug: "replica-set" },
          { label: "Deployment", slug: "deployment" },
        ],
      },
    },
    {
      id: "scheduler",
      label: "Scheduler",
      subtitle: "binds pods → nodes",
      x: 56,
      y: 46,
      kind: "control",
      inspector: {
        what: "Chooses a node for each Pending pod using filters and scores.",
        receives: "Unscheduled Pod objects.",
        returns: "A binding: spec.nodeName.",
        why: "Capacity, taints, affinity, and GPU requests are decided here — not by kubelet lottery.",
        related: [
          { label: "Node", slug: "node" },
          { label: "Requests / limits", slug: "requests-limits" },
        ],
      },
    },
    {
      id: "node-a",
      label: "Node A",
      subtitle: "kubelet + runtime",
      x: 22,
      y: 78,
      kind: "server",
      inspector: {
        what: "A worker. kubelet watches assigned pods and asks the runtime to run them.",
        receives: "Pod specs bound to this node.",
        returns: "Container status, probes, logs.",
        why: "The control plane decides. The node makes processes exist.",
        related: [
          { label: "kubelet", slug: "kubelet" },
          { label: "Container runtime", slug: "container-runtime" },
        ],
      },
    },
    {
      id: "node-b",
      label: "Node B",
      subtitle: "kubelet + runtime",
      x: 50,
      y: 78,
      kind: "server",
      inspector: {
        what: "A second worker so replicas can spread.",
        receives: "Pod specs bound here.",
        returns: "Running containers.",
        why: "A node death should not take every replica if the scheduler spread them.",
        related: [{ label: "Node", slug: "node" }, { label: "Pod", slug: "pod" }],
      },
    },
    {
      id: "pod-1",
      label: "Pod web-1",
      subtitle: "replica",
      x: 78,
      y: 66,
      kind: "process",
      inspector: {
        what: "The smallest deployable unit: one or more containers sharing a network namespace.",
        receives: "An image and a restart policy.",
        returns: "A Ready or not-Ready signal.",
        why: "Controllers reason about pods, not containers.",
        related: [
          { label: "Pod", slug: "pod" },
          { label: "Probes", slug: "probes" },
        ],
      },
    },
    {
      id: "pod-2",
      label: "Pod web-2",
      subtitle: "replica",
      x: 92,
      y: 66,
      kind: "process",
      inspector: {
        what: "A second identical replica.",
        receives: "The same pod template.",
        returns: "Independent process health.",
        why: "Replicas are copies, not shards. Each can die alone.",
        related: [{ label: "ReplicaSet", slug: "replica-set" }],
      },
    },
    {
      id: "pod-3",
      label: "Pod web-3",
      subtitle: "replica",
      x: 80,
      y: 84,
      kind: "process",
      inspector: {
        what: "The third replica that restores desired=3 after a failure.",
        receives: "A newly scheduled pod spec.",
        returns: "Ready once the runtime starts it.",
        why: "You never “restart the dead one.” You create a replacement.",
        related: [{ label: "Deployment", slug: "deployment" }],
      },
    },
  ],
  edges: [
    { id: "k-api", from: "kubectl", to: "apiserver" },
    { id: "api-etcd", from: "apiserver", to: "etcd", bidirectional: true },
    { id: "api-ctrl", from: "apiserver", to: "controller", bidirectional: true },
    { id: "api-sch", from: "apiserver", to: "scheduler", bidirectional: true },
    { id: "ctrl-api", from: "controller", to: "apiserver" },
    { id: "sch-a", from: "scheduler", to: "node-a" },
    { id: "sch-b", from: "scheduler", to: "node-b" },
    { id: "a-p1", from: "node-a", to: "pod-1" },
    { id: "b-p2", from: "node-b", to: "pod-2" },
    { id: "a-p3", from: "node-a", to: "pod-3" },
  ],
  zones: [
    {
      id: "cp",
      label: "Control plane",
      x: 24,
      y: 4,
      width: 46,
      height: 56,
      kind: "control",
    },
    {
      id: "workers",
      label: "Workers",
      x: 14,
      y: 64,
      width: 48,
      height: 30,
      kind: "cluster",
    },
  ],
  initialStates: {
    kubectl: { status: "apply Deployment" },
    apiserver: { status: "idle" },
    etcd: { status: "empty deploy" },
    controller: { status: "watching", desired: 3, actual: 0 },
    scheduler: { status: "idle" },
    "node-a": { status: "ready" },
    "node-b": { status: "ready" },
    "pod-1": { status: "missing", visible: false },
    "pod-2": { status: "missing", visible: false },
    "pod-3": { status: "missing", visible: false },
  },
  steps: [
    {
      id: "apply",
      title: "Declare replicas: 3",
      explanation: "kubectl does not start containers. It writes a wish.",
      duration: 2300,
      events: [
        { type: "highlight", nodeIds: ["kubectl", "apiserver"] },
        {
          type: "packet",
          from: "kubectl",
          to: "apiserver",
          label: "POST Deployment spec.replicas=3",
          kind: "control",
          duration: 900,
        },
        {
          type: "state",
          nodeId: "apiserver",
          patch: { status: "admitted" },
          delay: 950,
        },
      ],
    },
    {
      id: "persist",
      title: "Desired state is stored",
      explanation: "The API server persists the object. etcd is now the source of truth.",
      duration: 2300,
      events: [
        { type: "highlight", nodeIds: ["apiserver", "etcd"] },
        {
          type: "packet",
          from: "apiserver",
          to: "etcd",
          label: "write /deployments/web",
          kind: "data",
          duration: 800,
        },
        {
          type: "state",
          nodeId: "etcd",
          patch: { status: "desired replicas=3" },
          delay: 850,
        },
      ],
    },
    {
      id: "notice",
      title: "Controller notices drift",
      explanation: "desired=3, actual=0. The loop has work.",
      duration: 2600,
      events: [
        { type: "highlight", nodeIds: ["etcd", "controller"] },
        {
          type: "packet",
          from: "apiserver",
          to: "controller",
          label: "watch: Deployment added",
          kind: "control",
          duration: 800,
        },
        {
          type: "state",
          nodeId: "controller",
          patch: { status: "reconciling", desired: 3, actual: 0 },
          delay: 850,
        },
        {
          type: "explain",
          text: "Controllers never “remember to start things.” They observe and repair.",
          delay: 900,
        },
      ],
    },
    {
      id: "create-pods",
      title: "Create missing pods",
      explanation: "The ReplicaSet controller creates three Pod objects — still Pending.",
      duration: 2600,
      events: [
        { type: "highlight", nodeIds: ["controller", "apiserver", "pod-1", "pod-2", "pod-3"] },
        {
          type: "packet",
          from: "controller",
          to: "apiserver",
          label: "create Pod ×3",
          kind: "control",
          duration: 800,
        },
        {
          type: "state",
          nodeId: "pod-1",
          patch: { visible: true, status: "Pending" },
          delay: 850,
        },
        {
          type: "state",
          nodeId: "pod-2",
          patch: { visible: true, status: "Pending" },
          delay: 850,
        },
        {
          type: "state",
          nodeId: "pod-3",
          patch: { visible: true, status: "Pending" },
          delay: 850,
        },
        {
          type: "state",
          nodeId: "controller",
          patch: { actual: 3, status: "pods created" },
          delay: 900,
        },
      ],
    },
    {
      id: "schedule",
      title: "Scheduler binds nodes",
      explanation: "Pending pods have no node. The scheduler picks one for each.",
      duration: 2800,
      events: [
        { type: "highlight", nodeIds: ["scheduler", "node-a", "node-b"] },
        {
          type: "packet",
          from: "apiserver",
          to: "scheduler",
          label: "watch Pending",
          kind: "control",
          duration: 700,
        },
        {
          type: "packet",
          from: "scheduler",
          to: "node-a",
          label: "bind web-1, web-3",
          kind: "control",
          delay: 800,
          duration: 800,
        },
        {
          type: "packet",
          from: "scheduler",
          to: "node-b",
          label: "bind web-2",
          kind: "control",
          delay: 900,
          duration: 800,
        },
        {
          type: "state",
          nodeId: "pod-1",
          patch: { status: "Bound A" },
          delay: 1600,
        },
        {
          type: "state",
          nodeId: "pod-2",
          patch: { status: "Bound B" },
          delay: 1600,
        },
        {
          type: "state",
          nodeId: "pod-3",
          patch: { status: "Bound A" },
          delay: 1600,
        },
      ],
    },
    {
      id: "start",
      title: "kubelets start containers",
      explanation: "Each kubelet pulls the image and asks the runtime to start the pod.",
      duration: 2800,
      events: [
        { type: "highlight", nodeIds: ["node-a", "node-b", "pod-1", "pod-2", "pod-3"] },
        {
          type: "packet",
          from: "node-a",
          to: "pod-1",
          label: "runtime start",
          kind: "data",
          duration: 800,
        },
        {
          type: "packet",
          from: "node-b",
          to: "pod-2",
          label: "runtime start",
          kind: "data",
          delay: 150,
          duration: 800,
        },
        {
          type: "packet",
          from: "node-a",
          to: "pod-3",
          label: "runtime start",
          kind: "data",
          delay: 300,
          duration: 800,
        },
        {
          type: "state",
          nodeId: "pod-1",
          patch: { status: "Running  Ready" },
          delay: 900,
        },
        {
          type: "state",
          nodeId: "pod-2",
          patch: { status: "Running  Ready" },
          delay: 1000,
        },
        {
          type: "state",
          nodeId: "pod-3",
          patch: { status: "Running  Ready" },
          delay: 1100,
        },
        {
          type: "state",
          nodeId: "controller",
          patch: { status: "healthy", desired: 3, actual: 3 },
          delay: 1200,
        },
      ],
    },
    {
      id: "die",
      title: "A pod disappears",
      explanation: "web-2 dies. Desired is still 3. Reality is now 2.",
      duration: 2600,
      events: [
        { type: "highlight", nodeIds: ["pod-2", "controller"] },
        {
          type: "state",
          nodeId: "pod-2",
          patch: { status: "Terminated", visible: true },
        },
        {
          type: "packet",
          from: "node-b",
          to: "apiserver",
          label: "status: Failed",
          kind: "error",
          delay: 400,
          duration: 800,
        },
        {
          type: "state",
          nodeId: "controller",
          patch: { status: "drift", desired: 3, actual: 2 },
          delay: 1200,
        },
        {
          type: "explain",
          text: "Nobody pages a human to “restart pod 2.” The loop sees the math.",
          delay: 1250,
        },
      ],
    },
    {
      id: "replace",
      title: "Replacement is scheduled",
      explanation: "A new pod object is created and bound. The dead name is not revived.",
      duration: 2800,
      events: [
        { type: "highlight", nodeIds: ["controller", "scheduler", "pod-2"] },
        {
          type: "packet",
          from: "controller",
          to: "apiserver",
          label: "create replacement pod",
          kind: "control",
          duration: 800,
        },
        {
          type: "state",
          nodeId: "pod-2",
          patch: { status: "Pending (new)", label: "web-4" },
          delay: 850,
        },
        {
          type: "packet",
          from: "scheduler",
          to: "node-b",
          label: "bind replacement",
          kind: "control",
          delay: 1000,
          duration: 800,
        },
      ],
    },
    {
      id: "restored",
      title: "Healthy state restored",
      explanation: "desired=3, actual=3. The loop goes quiet until the next drift.",
      duration: 2600,
      events: [
        { type: "highlight", nodeIds: ["pod-1", "pod-2", "pod-3", "controller"] },
        {
          type: "packet",
          from: "node-b",
          to: "pod-2",
          label: "runtime start",
          kind: "data",
          duration: 800,
        },
        {
          type: "state",
          nodeId: "pod-2",
          patch: { status: "Running  Ready" },
          delay: 850,
        },
        {
          type: "state",
          nodeId: "controller",
          patch: { status: "reconciled", desired: 3, actual: 3 },
          delay: 900,
        },
        {
          type: "explain",
          text: "That loop — observe, diff, act — is the whole design.",
          delay: 950,
        },
      ],
    },
  ],
};
