import type { SimulationDefinition } from "@/lib/types";

export const otelSimulation: SimulationDefinition = {
  id: "otel",
  nodes: [
    {
      id: "browser",
      label: "Browser",
      subtitle: "traceparent",
      x: 10,
      y: 22,
      kind: "client",
      inspector: {
        what: "Starts a request and may start the trace.",
        receives: "A click.",
        returns: "An HTTP call with a trace context header.",
        why: "If the header is missing, the backend invents a new trace.",
        related: [{ label: "Traces", slug: "traces" }, { label: "HTTP", slug: "http" }],
      },
    },
    {
      id: "gw",
      label: "API gateway",
      subtitle: "span: ingress",
      x: 32,
      y: 22,
      kind: "gateway",
      inspector: {
        what: "First server span. Records status and duration for the edge.",
        receives: "The request plus a trace id.",
        returns: "A child span context to Service A.",
        why: "This hop is where most 401s and 429s are born.",
        related: [{ label: "Spans", slug: "spans" }, { label: "Latency", slug: "latency" }],
      },
    },
    {
      id: "a",
      label: "Service A",
      subtitle: "span: checkout",
      x: 54,
      y: 22,
      kind: "server",
      inspector: {
        what: "Business logic. Parent of B and of the DB span.",
        receives: "A traced inbound request.",
        returns: "A response, plus child spans.",
        why: "This is where time usually hides — not in the gateway.",
        related: [{ label: "OpenTelemetry", slug: "opentelemetry" }],
      },
    },
    {
      id: "b",
      label: "Service B",
      subtitle: "span: inventory",
      x: 76,
      y: 22,
      kind: "server",
      inspector: {
        what: "A dependency. Slow here looks like “A is slow” if you only have metrics.",
        receives: "An RPC with the same trace id.",
        returns: "A result and its own span.",
        why: "Traces exist because metrics cannot name the culprit hop.",
        related: [{ label: "Traces", slug: "traces" }, { label: "Latency", slug: "latency" }],
      },
    },
    {
      id: "db",
      label: "Database",
      subtitle: "span: query",
      x: 76,
      y: 56,
      kind: "storage",
      inspector: {
        what: "The leaf. Often the longest span.",
        receives: "SQL with a comment or driver hook.",
        returns: "Rows, and a duration.",
        why: "A 200 from A can still be a 90ms query you should have indexed.",
        related: [{ label: "Databases", slug: "databases" }, { label: "Spans", slug: "spans" }],
      },
    },
    {
      id: "trace",
      label: "Trace",
      subtitle: "4c2f…  142ms",
      x: 54,
      y: 56,
      kind: "control",
      inspector: {
        what: "One request’s causal tree: parent/child spans, same trace id.",
        receives: "Exported spans.",
        returns: "A waterfall: where the 142ms went.",
        why: "This answers “what happened to this user?”",
        related: [{ label: "Traces", slug: "traces" }, { label: "Spans", slug: "spans" }],
      },
    },
    {
      id: "metrics",
      label: "Metrics",
      subtitle: "p99 · rps · errors",
      x: 32,
      y: 56,
      kind: "queue",
      inspector: {
        what: "Aggregates. Cheap. Blind to a single request’s path.",
        receives: "Recorded durations and counters.",
        returns: "A shape over time.",
        why: "This answers “is the fleet sick?” — not “why was Josh slow?”",
        related: [
          { label: "Metrics", slug: "metrics" },
          { label: "Prometheus", slug: "prometheus" },
        ],
      },
    },
    {
      id: "logs",
      label: "Logs",
      subtitle: "trace_id=4c2f",
      x: 10,
      y: 56,
      kind: "storage",
      inspector: {
        what: "A diary of events, ideally stamped with the same trace id.",
        receives: "Structured lines from each service.",
        returns: "The story in words.",
        why: "This answers “what did the code think?” Traces say when. Logs say why.",
        related: [{ label: "Logs", slug: "logs" }, { label: "OpenTelemetry", slug: "opentelemetry" }],
      },
    },
  ],
  edges: [
    { id: "b-g", from: "browser", to: "gw" },
    { id: "g-a", from: "gw", to: "a" },
    { id: "a-b", from: "a", to: "b" },
    { id: "b-db", from: "b", to: "db", bidirectional: true },
    { id: "a-t", from: "a", to: "trace" },
    { id: "t-m", from: "trace", to: "metrics" },
    { id: "t-l", from: "trace", to: "logs" },
  ],
  zones: [
    {
      id: "path",
      label: "One request",
      x: 2,
      y: 8,
      width: 86,
      height: 28,
      kind: "public",
    },
    {
      id: "signals",
      label: "Three signals",
      x: 2,
      y: 42,
      width: 64,
      height: 30,
      kind: "control",
    },
  ],
  initialStates: {
    browser: { status: "click Checkout" },
    gw: { status: "no span" },
    a: { status: "no span" },
    b: { status: "no span" },
    db: { status: "idle" },
    trace: { status: "empty" },
    metrics: { status: "fleet view" },
    logs: { status: "quiet" },
  },
  steps: [
    {
      id: "start",
      title: "A request is born",
      explanation: "One checkout. We will watch the same call become three different pictures.",
      duration: 2200,
      events: [
        { type: "highlight", nodeIds: ["browser"] },
        { type: "state", nodeId: "browser", patch: { status: "trace 4c2f…" } },
      ],
    },
    {
      id: "gw",
      title: "Gateway span",
      explanation: "Ingress span starts. Duration is a stopwatch, not a story yet.",
      duration: 2300,
      events: [
        { type: "highlight", nodeIds: ["browser", "gw"] },
        {
          type: "packet",
          from: "browser",
          to: "gw",
          label: "GET /checkout  4c2f",
          kind: "http",
          duration: 800,
        },
        { type: "state", nodeId: "gw", patch: { status: "span 12ms" }, delay: 850 },
        { type: "latency", nodeId: "gw", ms: 12, delay: 850 },
      ],
    },
    {
      id: "a",
      title: "Service A span",
      explanation: "A is the parent. Its children will explain its 142ms.",
      duration: 2300,
      events: [
        { type: "highlight", nodeIds: ["gw", "a"] },
        {
          type: "packet",
          from: "gw",
          to: "a",
          label: "span context",
          kind: "http",
          duration: 800,
        },
        { type: "state", nodeId: "a", patch: { status: "parent 142ms" }, delay: 850 },
        { type: "latency", nodeId: "a", ms: 142, delay: 850 },
      ],
    },
    {
      id: "b",
      title: "Service B child span",
      explanation: "Same trace id. New span id. Parent = A.",
      duration: 2300,
      events: [
        { type: "highlight", nodeIds: ["a", "b"] },
        {
          type: "packet",
          from: "a",
          to: "b",
          label: "child span",
          kind: "data",
          duration: 800,
        },
        { type: "state", nodeId: "b", patch: { status: "38ms" }, delay: 850 },
        { type: "latency", nodeId: "b", ms: 38, delay: 850 },
      ],
    },
    {
      id: "db",
      title: "Query span",
      explanation: "The leaf ate 80ms. That is the story metrics would hide in an average.",
      duration: 2600,
      events: [
        { type: "highlight", nodeIds: ["b", "db"] },
        {
          type: "packet",
          from: "b",
          to: "db",
          label: "SELECT inventory",
          kind: "query",
          duration: 900,
        },
        { type: "state", nodeId: "db", patch: { status: "80ms" }, delay: 950 },
        { type: "latency", nodeId: "db", ms: 80, delay: 950 },
        {
          type: "packet",
          from: "db",
          to: "b",
          label: "rows",
          kind: "response",
          delay: 1100,
          duration: 700,
        },
      ],
    },
    {
      id: "tree",
      title: "The trace assembles",
      explanation: "One id. A tree. You can see parent/child and where 142ms went.",
      duration: 2600,
      events: [
        { type: "highlight", nodeIds: ["a", "trace"] },
        {
          type: "packet",
          from: "a",
          to: "trace",
          label: "export spans",
          kind: "data",
          duration: 800,
        },
        {
          type: "state",
          nodeId: "trace",
          patch: { status: "4c2f  gw→A→B→db" },
          delay: 850,
        },
      ],
    },
    {
      id: "split",
      title: "Same request, three signals",
      explanation: "Metrics count it. Logs describe it. The trace places it.",
      duration: 3000,
      events: [
        { type: "highlight", nodeIds: ["trace", "metrics", "logs"] },
        {
          type: "packet",
          from: "trace",
          to: "metrics",
          label: "checkout_latency_ms=142",
          kind: "control",
          duration: 800,
        },
        {
          type: "packet",
          from: "trace",
          to: "logs",
          label: "trace_id=4c2f reserved=ok",
          kind: "data",
          delay: 200,
          duration: 800,
        },
        { type: "state", nodeId: "metrics", patch: { status: "p99 += this point" }, delay: 900 },
        { type: "state", nodeId: "logs", patch: { status: "3 lines  one id" }, delay: 1050 },
        {
          type: "explain",
          text: "Metrics: the fleet. Logs: the words. Traces: this request’s path.",
          delay: 1100,
        },
      ],
    },
  ],
};
