import type { SimulationDefinition } from "@/lib/types";

export const pipesSimulation: SimulationDefinition = {
  id: "pipes",
  nodes: [
    {
      id: "user",
      label: "You",
      subtitle: "ls | grep api",
      x: 10,
      y: 22,
      kind: "client",
      inspector: {
        what: "A human typed one line. The shell will turn it into two processes and a kernel buffer.",
        receives: "Keystrokes.",
        returns: "A command line for the shell.",
        why: "The pipe character is not grep’s problem. It is the shell’s.",
        related: [{ label: "Shell", slug: "shell" }, { label: "Terminal", slug: "terminal" }],
      },
    },
    {
      id: "shell",
      label: "Shell",
      subtitle: "bash / zsh",
      x: 34,
      y: 22,
      kind: "control",
      inspector: {
        what: "Parses the line, creates a pipe, then forks ls and grep.",
        receives: "A command string.",
        returns: "Child processes with fds already wired.",
        why: "ls never hears about grep. It only writes to fd 1.",
        related: [
          { label: "Pipes", slug: "pipes" },
          { label: "File descriptors", slug: "file-descriptors" },
        ],
      },
    },
    {
      id: "ls",
      label: "ls process",
      subtitle: "stdout → pipe",
      x: 58,
      y: 22,
      kind: "process",
      inspector: {
        what: "Lists names. It thinks it is printing to the terminal. It is not.",
        receives: "A directory, via argv.",
        returns: "Lines on file descriptor 1.",
        why: "Programs stay simple because the shell remaps their fds.",
        related: [{ label: "stdout", slug: "stdout" }, { label: "Processes", slug: "linux-processes" }],
      },
    },
    {
      id: "pipe",
      label: "Pipe",
      subtitle: "kernel buffer",
      x: 58,
      y: 56,
      kind: "queue",
      inspector: {
        what: "A kernel FIFO: one writer, one reader, a few pages of buffer.",
        receives: "Bytes from ls’s stdout.",
        returns: "Those bytes to grep’s stdin.",
        why: "This is the `|`. Not a file. Not a network. A tube.",
        related: [{ label: "stdin", slug: "stdin" }, { label: "stdout", slug: "stdout" }],
      },
    },
    {
      id: "grep",
      label: "grep process",
      subtitle: "filter “api”",
      x: 82,
      y: 56,
      kind: "process",
      inspector: {
        what: "Reads lines and keeps the ones that match.",
        receives: "stdin from the pipe.",
        returns: "Matching lines on its own stdout.",
        why: "It never opened the directory. It only saw a stream.",
        related: [{ label: "stdin", slug: "stdin" }, { label: "stderr", slug: "stderr" }],
      },
    },
    {
      id: "term",
      label: "Terminal",
      subtitle: "the window",
      x: 82,
      y: 22,
      kind: "client",
      inspector: {
        what: "Displays whatever lands on the last process’s stdout.",
        receives: "grep’s surviving lines.",
        returns: "Pixels you can read.",
        why: "You see the filter’s output, not ls’s full listing.",
        related: [{ label: "Terminal", slug: "terminal" }, { label: "stdout", slug: "stdout" }],
      },
    },
  ],
  edges: [
    { id: "u-s", from: "user", to: "shell" },
    { id: "s-ls", from: "shell", to: "ls" },
    { id: "s-p", from: "shell", to: "pipe" },
    { id: "s-g", from: "shell", to: "grep" },
    { id: "ls-p", from: "ls", to: "pipe" },
    { id: "p-g", from: "pipe", to: "grep" },
    { id: "g-t", from: "grep", to: "term" },
  ],
  zones: [
    {
      id: "kernel-pipe",
      label: "Inside the kernel",
      x: 46,
      y: 42,
      width: 26,
      height: 32,
      kind: "host",
    },
  ],
  initialStates: {
    user: { status: "types a line" },
    shell: { status: "idle" },
    ls: { status: "not started" },
    pipe: { status: "no fds yet" },
    grep: { status: "not started" },
    term: { status: "waiting" },
  },
  steps: [
    {
      id: "type",
      title: "ls | grep api",
      explanation: "One line. The shell will turn it into two processes and a tube.",
      duration: 2200,
      events: [
        { type: "highlight", nodeIds: ["user", "shell"] },
        {
          type: "packet",
          from: "user",
          to: "shell",
          label: "ls | grep api",
          kind: "control",
          duration: 800,
        },
      ],
    },
    {
      id: "fork-ls",
      title: "Shell creates ls",
      explanation: "First child: ls. Its stdout is not the terminal yet.",
      duration: 2300,
      events: [
        { type: "highlight", nodeIds: ["shell", "ls"] },
        {
          type: "packet",
          from: "shell",
          to: "ls",
          label: "fork + exec ls",
          kind: "control",
          duration: 800,
        },
        { type: "state", nodeId: "ls", patch: { status: "PID 2201" }, delay: 850 },
      ],
    },
    {
      id: "pipe",
      title: "Shell creates a pipe",
      explanation: "pipe() returns two fds: a write end and a read end.",
      duration: 2400,
      events: [
        { type: "highlight", nodeIds: ["shell", "pipe"] },
        {
          type: "packet",
          from: "shell",
          to: "pipe",
          label: "pipe()  fd[0] fd[1]",
          kind: "control",
          duration: 800,
        },
        { type: "state", nodeId: "pipe", patch: { status: "empty buffer" }, delay: 850 },
        {
          type: "explain",
          text: "This object is the `|`. Everything else is just pointing fds at it.",
          delay: 900,
        },
      ],
    },
    {
      id: "fork-grep",
      title: "Shell creates grep",
      explanation: "Second child: grep. stdin is the pipe’s read end.",
      duration: 2400,
      events: [
        { type: "highlight", nodeIds: ["shell", "grep"] },
        {
          type: "packet",
          from: "shell",
          to: "grep",
          label: "fork + exec grep api",
          kind: "control",
          duration: 800,
        },
        { type: "state", nodeId: "grep", patch: { status: "PID 2202  stdin=pipe" }, delay: 850 },
        { type: "state", nodeId: "ls", patch: { status: "stdout=pipe" }, delay: 850 },
      ],
    },
    {
      id: "flow",
      title: "stdout flows through the pipe",
      explanation: "ls writes names. They sit in the kernel until grep reads.",
      duration: 2800,
      events: [
        { type: "highlight", nodeIds: ["ls", "pipe", "grep"] },
        {
          type: "packet",
          from: "ls",
          to: "pipe",
          label: "api-gateway",
          kind: "data",
          duration: 700,
        },
        {
          type: "packet",
          from: "ls",
          to: "pipe",
          label: "README.md",
          kind: "data",
          delay: 200,
          duration: 700,
        },
        {
          type: "packet",
          from: "ls",
          to: "pipe",
          label: "api-server",
          kind: "data",
          delay: 400,
          duration: 700,
        },
        { type: "state", nodeId: "pipe", patch: { status: "3 lines buffered" }, delay: 900 },
      ],
    },
    {
      id: "filter",
      title: "grep filters",
      explanation: "README.md dies in grep. Only lines containing “api” continue.",
      duration: 2600,
      events: [
        { type: "highlight", nodeIds: ["pipe", "grep"] },
        {
          type: "packet",
          from: "pipe",
          to: "grep",
          label: "stream",
          kind: "data",
          duration: 800,
        },
        { type: "state", nodeId: "grep", patch: { status: "kept 2 / dropped 1" }, delay: 850 },
      ],
    },
    {
      id: "out",
      title: "Terminal receives output",
      explanation: "grep’s stdout is the window. You never saw the full listing.",
      duration: 2600,
      events: [
        { type: "highlight", nodeIds: ["grep", "term"] },
        {
          type: "packet",
          from: "grep",
          to: "term",
          label: "api-gateway",
          kind: "response",
          duration: 700,
        },
        {
          type: "packet",
          from: "grep",
          to: "term",
          label: "api-server",
          kind: "response",
          delay: 250,
          duration: 700,
        },
        { type: "state", nodeId: "term", patch: { status: "2 lines shown" }, delay: 1000 },
        {
          type: "explain",
          text: "Two processes. One kernel buffer. That is a pipe.",
          delay: 1050,
        },
      ],
    },
  ],
};
