import type { SimulationDefinition } from "@/lib/types";

export const platformSimulation: SimulationDefinition = {
  id: "platform",
  nodes: [
    {
      id: "dev",
      label: "Developer",
      subtitle: "Create API Service",
      x: 10,
      y: 22,
      kind: "client",
      inspector: {
        what: "Asks for a service, not a subnet. The form is the product.",
        receives: "A name, a team, a template.",
        returns: "A ticketless request to the platform API.",
        why: "If this needs Slack, it is not self-service yet.",
        related: [
          { label: "Self-service", slug: "self-service" },
          { label: "Golden path", slug: "golden-path" },
        ],
      },
    },
    {
      id: "portal",
      label: "Developer portal",
      subtitle: "the lobby",
      x: 32,
      y: 22,
      kind: "client",
      inspector: {
        what: "Catalog, templates, docs. UX on top of the API.",
        receives: "A click on “API Service.”",
        returns: "A validated create request.",
        why: "The UI is optional. The contract behind it is not.",
        related: [
          { label: "Developer portal", slug: "developer-portal" },
          { label: "Service catalog", slug: "service-catalog" },
        ],
      },
    },
    {
      id: "api",
      label: "Platform API",
      subtitle: "the product",
      x: 54,
      y: 22,
      kind: "gateway",
      inspector: {
        what: "One interface over git, Terraform, Kubernetes, and CI.",
        receives: "CreateService.",
        returns: "A workflow id — then a URL.",
        why: "This is the platform. Everything else is machinery.",
        related: [
          { label: "Platform API", slug: "platform-api" },
          { label: "Policy", slug: "policy" },
        ],
      },
    },
    {
      id: "git",
      label: "Git repo",
      subtitle: "minted from a template",
      x: 76,
      y: 22,
      kind: "storage",
      inspector: {
        what: "A new repository on the golden path: Dockerfile, CI, manifest stubs.",
        receives: "A template render.",
        returns: "A default branch CI can run.",
        why: "Day-1 consistency is cheaper than day-400 cleanup.",
        related: [{ label: "Templates", slug: "templates" }, { label: "GitOps", slug: "gitops" }],
      },
    },
    {
      id: "tf",
      label: "Terraform",
      subtitle: "cloud resources",
      x: 76,
      y: 56,
      kind: "control",
      inspector: {
        what: "Creates the hidden bits: IAM, DNS, a database if the template asked.",
        receives: "A module call from the platform.",
        returns: "IDs written back to the catalog.",
        why: "The developer ordered a kitchen. This lays the pipes.",
        related: [
          { label: "Terraform", slug: "terraform" },
          { label: "Infrastructure abstraction", slug: "infrastructure-abstraction" },
        ],
      },
    },
    {
      id: "k8s",
      label: "Kubernetes",
      subtitle: "namespace + deploy",
      x: 54,
      y: 56,
      kind: "server",
      inspector: {
        what: "Where the process will run. The developer never kubectl’d.",
        receives: "A desired deployment.",
        returns: "Ready pods.",
        why: "The paved road includes placement, probes, and limits.",
        related: [
          { label: "Deployment", slug: "deployment" },
          { label: "Namespace", slug: "namespace" },
        ],
      },
    },
    {
      id: "ci",
      label: "CI / CD",
      subtitle: "first pipeline",
      x: 32,
      y: 56,
      kind: "runtime",
      inspector: {
        what: "The first build of the minted repo.",
        receives: "The initial commit.",
        returns: "An image and a deploy.",
        why: "A template without a green pipeline is a brochure.",
        related: [{ label: "Pipeline", slug: "pipeline" }, { label: "CI", slug: "ci" }],
      },
    },
    {
      id: "obs",
      label: "Observability",
      subtitle: "on by default",
      x: 10,
      y: 56,
      kind: "control",
      inspector: {
        what: "Dashboards, logs, traces wired by the path — not by a later ticket.",
        receives: "The new service identity.",
        returns: "A folder the team already owns.",
        why: "If gold-path services are dark, the path is incomplete.",
        related: [
          { label: "OpenTelemetry", slug: "opentelemetry" },
          { label: "Developer experience", slug: "developer-experience" },
        ],
      },
    },
    {
      id: "url",
      label: "URL returned",
      subtitle: "checkout.dev.example",
      x: 10,
      y: 74,
      kind: "network",
      inspector: {
        what: "The only thing the developer asked to see.",
        receives: "DNS + ingress from the workflow.",
        returns: "A link in the portal.",
        why: "The platform hid a dozen systems on purpose.",
        related: [{ label: "Paved roads", slug: "paved-roads" }],
      },
    },
  ],
  edges: [
    { id: "d-p", from: "dev", to: "portal" },
    { id: "p-a", from: "portal", to: "api" },
    { id: "a-g", from: "api", to: "git" },
    { id: "a-t", from: "api", to: "tf" },
    { id: "a-k", from: "api", to: "k8s" },
    { id: "g-c", from: "git", to: "ci" },
    { id: "c-k", from: "ci", to: "k8s" },
    { id: "a-o", from: "api", to: "obs" },
    { id: "a-u", from: "api", to: "url" },
  ],
  zones: [
    { id: "hidden", label: "Hidden on purpose", x: 24, y: 42, width: 64, height: 30, kind: "host" },
  ],
  initialStates: {
    dev: { status: "picks a template" },
    portal: { status: "catalog" },
    api: { status: "idle" },
    git: { status: "—" },
    tf: { status: "—" },
    k8s: { status: "—" },
    ci: { status: "—" },
    obs: { status: "—" },
    url: { status: "not yet", visible: true },
  },
  steps: [
    {
      id: "click",
      title: "Create API Service",
      explanation: "The developer does not open Jira. They pick a paved road.",
      duration: 2200,
      events: [
        { type: "highlight", nodeIds: ["dev", "portal"] },
        {
          type: "packet",
          from: "dev",
          to: "portal",
          label: "template: api-service",
          kind: "control",
          duration: 800,
        },
      ],
    },
    {
      id: "api",
      title: "Platform API accepts",
      explanation: "Policy, tenancy, and naming happen here — not in a wiki.",
      duration: 2300,
      events: [
        { type: "highlight", nodeIds: ["portal", "api"] },
        {
          type: "packet",
          from: "portal",
          to: "api",
          label: "POST /services",
          kind: "http",
          duration: 800,
        },
        { type: "state", nodeId: "api", patch: { status: "workflow started" }, delay: 850 },
      ],
    },
    {
      id: "git",
      title: "Repository minted",
      explanation: "A repo appears with CI, Dockerfile, and a CODEOWNERS already set.",
      duration: 2400,
      events: [
        { type: "highlight", nodeIds: ["api", "git"] },
        {
          type: "packet",
          from: "api",
          to: "git",
          label: "create from template",
          kind: "control",
          duration: 800,
        },
        { type: "state", nodeId: "git", patch: { status: "acme/checkout" }, delay: 850 },
      ],
    },
    {
      id: "tf",
      title: "Cloud resources",
      explanation: "IAM, DNS, maybe RDS. The form said “API,” not “three subnets.”",
      duration: 2500,
      events: [
        { type: "highlight", nodeIds: ["api", "tf"] },
        {
          type: "packet",
          from: "api",
          to: "tf",
          label: "apply module.service",
          kind: "control",
          duration: 900,
        },
        { type: "state", nodeId: "tf", patch: { status: "role + DNS" }, delay: 950 },
      ],
    },
    {
      id: "k8s",
      title: "Kubernetes",
      explanation: "Namespace, deploy, service, probes — the defaults of this company.",
      duration: 2400,
      events: [
        { type: "highlight", nodeIds: ["api", "k8s"] },
        {
          type: "packet",
          from: "api",
          to: "k8s",
          label: "apply Deployment",
          kind: "control",
          duration: 800,
        },
        { type: "state", nodeId: "k8s", patch: { status: "ns/checkout Ready" }, delay: 850 },
      ],
    },
    {
      id: "ci",
      title: "First pipeline",
      explanation: "The minted repo builds itself. Green is part of the path.",
      duration: 2400,
      events: [
        { type: "highlight", nodeIds: ["git", "ci", "k8s"] },
        {
          type: "packet",
          from: "git",
          to: "ci",
          label: "push main",
          kind: "data",
          duration: 800,
        },
        { type: "state", nodeId: "ci", patch: { status: "green  image tagged" }, delay: 850 },
      ],
    },
    {
      id: "obs",
      title: "Observability attached",
      explanation: "A dashboard folder exists before the first incident.",
      duration: 2300,
      events: [
        { type: "highlight", nodeIds: ["api", "obs"] },
        {
          type: "packet",
          from: "api",
          to: "obs",
          label: "register service",
          kind: "control",
          duration: 800,
        },
        { type: "state", nodeId: "obs", patch: { status: "logs + traces on" }, delay: 850 },
      ],
    },
    {
      id: "url",
      title: "A URL comes back",
      explanation: "The developer sees a link. The machinery stays backstage.",
      duration: 2600,
      events: [
        { type: "highlight", nodeIds: ["api", "url", "dev"] },
        {
          type: "packet",
          from: "api",
          to: "url",
          label: "https://checkout.dev.example",
          kind: "response",
          duration: 800,
        },
        { type: "state", nodeId: "url", patch: { status: "ready" }, delay: 850 },
        {
          type: "explain",
          text: "That is platform engineering: a product that hides the stack on purpose.",
          delay: 900,
        },
      ],
    },
  ],
};
