import type { SimulationDefinition } from "@/lib/types";

export const processSimulation: SimulationDefinition = {
  id: "process",
  nodes: [
    {
      id: "file",
      label: "Program file",
      subtitle: "/usr/local/bin/app",
      x: 10,
      y: 28,
      kind: "storage",
      inspector: {
        what: "Bytes on disk: an executable image, not a running program.",
        receives: "A path from the shell.",
        returns: "The file contents the kernel will map.",
        why: "Until exec, this is just storage.",
        related: [
          { label: "Filesystem", slug: "filesystem" },
          { label: "Storage", slug: "storage" },
        ],
      },
    },
    {
      id: "kernel",
      label: "Kernel",
      subtitle: "exec + mm + sched",
      x: 34,
      y: 28,
      kind: "control",
      inspector: {
        what: "The privileged code that creates processes and maps memory.",
        receives: "An execve system call.",
        returns: "A new task with an address space.",
        why: "User space cannot invent a process. It can only ask.",
        related: [
          { label: "System calls", slug: "system-calls" },
          { label: "Kernel", slug: "kernel" },
        ],
      },
    },
    {
      id: "process",
      label: "Process",
      subtitle: "PID 18422",
      x: 58,
      y: 28,
      kind: "process",
      inspector: {
        what: "A running program: address space, credentials, open files.",
        receives: "A mapped executable and a first thread.",
        returns: "Work — until it exits.",
        why: "This is the unit the OS isolates and accounts.",
        related: [
          { label: "Threads", slug: "threads" },
          { label: "File descriptors", slug: "file-descriptors" },
        ],
      },
    },
    {
      id: "ram",
      label: "RAM",
      subtitle: "address space",
      x: 58,
      y: 62,
      kind: "storage",
      inspector: {
        what: "The process’s virtual memory: code, heap, stack.",
        receives: "Page allocations from the kernel.",
        returns: "Bytes the CPU can actually touch.",
        why: "The file on disk is not what executes. The mapped pages are.",
        related: [{ label: "RAM", slug: "ram" }, { label: "CPU", slug: "cpu" }],
      },
    },
    {
      id: "thread",
      label: "Thread",
      subtitle: "runnable",
      x: 82,
      y: 28,
      kind: "process",
      inspector: {
        what: "The execution context the scheduler actually picks.",
        receives: "A time slice on a core.",
        returns: "Retired instructions.",
        why: "A process is a container. A thread is what runs.",
        related: [
          { label: "CPU cores", slug: "cpu-cores" },
          { label: "Threads", slug: "threads" },
        ],
      },
    },
    {
      id: "cpu",
      label: "CPU",
      subtitle: "core 0",
      x: 82,
      y: 62,
      kind: "gpu",
      inspector: {
        what: "The hardware that fetches and executes instructions.",
        receives: "A scheduled thread.",
        returns: "Progress, or a wait for I/O.",
        why: "Everything above exists so this chip has something legal to run.",
        related: [{ label: "CPU", slug: "cpu" }, { label: "System calls", slug: "system-calls" }],
      },
    },
    {
      id: "disk",
      label: "File read",
      subtitle: "open / read",
      x: 34,
      y: 62,
      kind: "storage",
      inspector: {
        what: "A syscall that copies bytes from storage into the process.",
        receives: "A file descriptor.",
        returns: "Data on the heap or a buffer.",
        why: "Most programs spend their life waiting here, not computing.",
        related: [
          { label: "File descriptors", slug: "file-descriptors" },
          { label: "Storage", slug: "storage" },
        ],
      },
    },
  ],
  edges: [
    { id: "f-k", from: "file", to: "kernel" },
    { id: "k-p", from: "kernel", to: "process" },
    { id: "p-r", from: "process", to: "ram", bidirectional: true },
    { id: "p-t", from: "process", to: "thread" },
    { id: "t-c", from: "thread", to: "cpu", bidirectional: true },
    { id: "p-d", from: "process", to: "disk", bidirectional: true },
  ],
  zones: [
    {
      id: "os",
      label: "Operating system",
      x: 24,
      y: 12,
      width: 24,
      height: 64,
      kind: "control",
    },
  ],
  initialStates: {
    file: { status: "on disk" },
    kernel: { status: "idle" },
    process: { status: "does not exist", visible: true },
    ram: { status: "unmapped" },
    thread: { status: "none" },
    cpu: { status: "idle" },
    disk: { status: "closed" },
  },
  steps: [
    {
      id: "start",
      title: "Start Program",
      explanation: "The file is not a process. Someone has to ask the kernel to run it.",
      duration: 2200,
      events: [
        { type: "highlight", nodeIds: ["file"] },
        { type: "state", nodeId: "file", patch: { status: "execve(\"./app\")" } },
      ],
    },
    {
      id: "load",
      title: "OS loads the executable",
      explanation: "execve hands the kernel a path. The kernel opens the file and prepares an address space.",
      duration: 2400,
      events: [
        { type: "highlight", nodeIds: ["file", "kernel"] },
        {
          type: "packet",
          from: "file",
          to: "kernel",
          label: "execve /usr/local/bin/app",
          kind: "control",
          duration: 900,
        },
        {
          type: "state",
          nodeId: "kernel",
          patch: { status: "loading image" },
          delay: 950,
        },
      ],
    },
    {
      id: "create",
      title: "Process created",
      explanation: "A PID appears. Isolation starts here — this is a new task, not a function call.",
      duration: 2400,
      events: [
        { type: "highlight", nodeIds: ["kernel", "process"] },
        {
          type: "packet",
          from: "kernel",
          to: "process",
          label: "clone + exec",
          kind: "control",
          duration: 900,
        },
        {
          type: "state",
          nodeId: "process",
          patch: { status: "PID 18422" },
          delay: 950,
        },
      ],
    },
    {
      id: "mem",
      title: "Memory allocated",
      explanation: "Code, heap, and stack are mapped. The CPU still has not run a user instruction.",
      duration: 2400,
      events: [
        { type: "highlight", nodeIds: ["process", "ram"] },
        {
          type: "packet",
          from: "process",
          to: "ram",
          label: "mmap text/heap/stack",
          kind: "data",
          duration: 900,
        },
        { type: "state", nodeId: "ram", patch: { status: "pages mapped" }, delay: 950 },
      ],
    },
    {
      id: "thread",
      title: "Thread starts",
      explanation: "The first thread becomes runnable. The scheduler now has someone to pick.",
      duration: 2300,
      events: [
        { type: "highlight", nodeIds: ["process", "thread"] },
        {
          type: "packet",
          from: "process",
          to: "thread",
          label: "main thread",
          kind: "control",
          duration: 800,
        },
        { type: "state", nodeId: "thread", patch: { status: "runnable" }, delay: 850 },
      ],
    },
    {
      id: "sched",
      title: "CPU schedules the thread",
      explanation: "A core takes the thread. Instructions finally execute.",
      duration: 2500,
      events: [
        { type: "highlight", nodeIds: ["thread", "cpu"] },
        {
          type: "packet",
          from: "thread",
          to: "cpu",
          label: "dispatch",
          kind: "data",
          duration: 800,
        },
        { type: "state", nodeId: "cpu", patch: { status: "executing" }, delay: 850 },
        { type: "state", nodeId: "thread", patch: { status: "running" }, delay: 850 },
      ],
    },
    {
      id: "read",
      title: "Process reads a file",
      explanation: "A syscall. The thread leaves the CPU and waits on storage.",
      duration: 2600,
      events: [
        { type: "highlight", nodeIds: ["cpu", "process", "disk"] },
        {
          type: "packet",
          from: "process",
          to: "disk",
          label: "open + read config.yaml",
          kind: "query",
          duration: 900,
        },
        { type: "state", nodeId: "disk", patch: { status: "fd 3" }, delay: 950 },
        { type: "state", nodeId: "cpu", patch: { status: "blocked on I/O" }, delay: 950 },
        {
          type: "packet",
          from: "disk",
          to: "process",
          label: "bytes → buffer",
          kind: "response",
          delay: 1100,
          duration: 800,
        },
      ],
    },
    {
      id: "exit",
      title: "Process exits",
      explanation: "exit_group. The kernel reaps the PID. RAM and fds go back.",
      duration: 2400,
      events: [
        { type: "highlight", nodeIds: ["process", "kernel"] },
        {
          type: "packet",
          from: "process",
          to: "kernel",
          label: "exit(0)",
          kind: "control",
          duration: 800,
        },
        { type: "state", nodeId: "process", patch: { status: "zombie → reaped" }, delay: 850 },
        { type: "state", nodeId: "thread", patch: { status: "gone" }, delay: 850 },
        { type: "state", nodeId: "ram", patch: { status: "freed" }, delay: 850 },
        {
          type: "explain",
          text: "A program is a file. A process is a living kernel object. Then it isn’t.",
          delay: 900,
        },
      ],
    },
  ],
};
