import type { SimulationDefinition } from "@/lib/types";

export const terraformSimulation: SimulationDefinition = {
  id: "terraform",
  nodes: [
    {
      id: "config",
      label: "Configuration",
      subtitle: "desired state",
      x: 10,
      y: 24,
      kind: "control",
      inspector: {
        what: "A declarative file: “I want N instances of this shape.”",
        receives: "Edits from a human or a pipeline.",
        returns: "A graph of resources for the engine.",
        why: "You describe the end. You do not SSH the steps.",
        related: [
          { label: "Declarative infrastructure", slug: "declarative-infrastructure" },
          { label: "Variable", slug: "variable" },
        ],
      },
    },
    {
      id: "provider",
      label: "Provider",
      subtitle: "AWS plugin",
      x: 34,
      y: 24,
      kind: "runtime",
      inspector: {
        what: "The plugin that knows one cloud API.",
        receives: "Init, then plan/apply RPC.",
        returns: "CRUD against real resources.",
        why: "Terraform core does not know what an instance is.",
        related: [{ label: "Provider", slug: "provider" }, { label: "Resource", slug: "resource" }],
      },
    },
    {
      id: "state",
      label: "State",
      subtitle: "as-built memory",
      x: 34,
      y: 58,
      kind: "storage",
      inspector: {
        what: "Terraform’s record of what it last created and the IDs.",
        receives: "Reads before plan, writes after apply.",
        returns: "The last known mapping of address → real object.",
        why: "Without this file, there is no diff — only guesswork.",
        related: [{ label: "State", slug: "state" }, { label: "Remote state", slug: "remote-state" }],
      },
    },
    {
      id: "cloud",
      label: "Real cloud",
      subtitle: "live API",
      x: 58,
      y: 58,
      kind: "server",
      inspector: {
        what: "The actual account. It may have drifted from state.",
        receives: "Describe calls, then create/update/delete.",
        returns: "Objects that cost money.",
        why: "Plan reads it. Apply writes it. The console can lie to state.",
        related: [{ label: "Drift", slug: "drift" }, { label: "Apply", slug: "apply" }],
      },
    },
    {
      id: "plan",
      label: "Plan",
      subtitle: "the diff",
      x: 58,
      y: 24,
      kind: "control",
      inspector: {
        what: "Desired minus (state refreshed from the cloud).",
        receives: "Config + state + live refresh.",
        returns: "A change set: +create / ~update / -destroy.",
        why: "Read this like blast radius. This is the last cheap moment.",
        related: [{ label: "Plan", slug: "plan" }, { label: "Apply", slug: "apply" }],
      },
    },
    {
      id: "api",
      label: "Cloud API",
      subtitle: "RunInstances",
      x: 82,
      y: 24,
      kind: "gateway",
      inspector: {
        what: "The HTTP/gRPC call that actually mutates the account.",
        receives: "A provider request during apply.",
        returns: "A new resource id.",
        why: "This is when money and outages happen.",
        related: [{ label: "Apply", slug: "apply" }, { label: "IAM", slug: "iam" }],
      },
    },
    {
      id: "instances",
      label: "Instances",
      subtitle: "web[count]",
      x: 82,
      y: 58,
      kind: "server",
      inspector: {
        what: "The machines that exist after apply.",
        receives: "Create calls.",
        returns: "Running compute.",
        why: "count = 2 → 3 means “add one.” Terraform does not rebuild the two.",
        related: [
          { label: "Virtual machines", slug: "virtual-machines" },
          { label: "Resource", slug: "resource" },
        ],
      },
    },
  ],
  edges: [
    { id: "c-p", from: "config", to: "provider" },
    { id: "p-s", from: "provider", to: "state", bidirectional: true },
    { id: "s-cloud", from: "state", to: "cloud", bidirectional: true },
    { id: "p-plan", from: "provider", to: "plan" },
    { id: "cloud-plan", from: "cloud", to: "plan" },
    { id: "plan-api", from: "plan", to: "api" },
    { id: "api-i", from: "api", to: "instances" },
    { id: "i-s", from: "instances", to: "state" },
  ],
  zones: [
    {
      id: "engine",
      label: "Terraform",
      x: 24,
      y: 8,
      width: 46,
      height: 66,
      kind: "control",
    },
  ],
  initialStates: {
    config: { status: "count = 2" },
    provider: { status: "not initialized" },
    state: { status: "web[0], web[1]" },
    cloud: { status: "2 instances live" },
    plan: { status: "no diff yet" },
    api: { status: "idle" },
    instances: { status: "2 running" },
  },
  selectControls: [
    {
      id: "count",
      label: "Desired instance count",
      defaultValue: "2",
      options: [
        { label: "2 instances", value: "2" },
        { label: "3 instances", value: "3" },
      ],
    },
  ],
  controlEffects: {
    count: {
      "2": {
        caption: "Desired is 2. State already has 2. The plan should be empty.",
        states: {
          config: { status: "count = 2" },
          plan: { status: "no-op" },
        },
      },
      "3": {
        caption: "Desired is 3. State has 2. Plan: +1 create. The two existing stay.",
        states: {
          config: { status: "count = 3" },
          plan: { status: "+ web[2]  create" },
        },
      },
    },
  },
  steps: [
    {
      id: "config",
      title: "Desired state on disk",
      explanation: "The file says how many instances should exist. Nothing has been called yet.",
      duration: 2200,
      events: [
        { type: "highlight", nodeIds: ["config"] },
        { type: "state", nodeId: "config", patch: { status: "aws_instance.web" } },
      ],
    },
    {
      id: "init",
      title: "Provider initialization",
      explanation: "terraform init downloads the AWS plugin. Core still does not know EC2.",
      duration: 2300,
      events: [
        { type: "highlight", nodeIds: ["config", "provider"] },
        {
          type: "packet",
          from: "config",
          to: "provider",
          label: "init hashicorp/aws",
          kind: "control",
          duration: 900,
        },
        { type: "state", nodeId: "provider", patch: { status: "ready" }, delay: 950 },
      ],
    },
    {
      id: "state",
      title: "Read current state",
      explanation: "State remembers web[0] and web[1]. That is Terraform’s memory, not the cloud’s.",
      duration: 2300,
      events: [
        { type: "highlight", nodeIds: ["provider", "state"] },
        {
          type: "packet",
          from: "provider",
          to: "state",
          label: "read terraform.tfstate",
          kind: "query",
          duration: 800,
        },
        { type: "state", nodeId: "state", patch: { status: "2 ids stored" }, delay: 850 },
      ],
    },
    {
      id: "refresh",
      title: "Inspect the real cloud",
      explanation: "Refresh asks the API: do those IDs still exist? Drift would show up here.",
      duration: 2500,
      events: [
        { type: "highlight", nodeIds: ["state", "cloud"] },
        {
          type: "packet",
          from: "state",
          to: "cloud",
          label: "DescribeInstances",
          kind: "query",
          duration: 900,
        },
        {
          type: "packet",
          from: "cloud",
          to: "state",
          label: "both still running",
          kind: "response",
          delay: 1000,
          duration: 800,
        },
      ],
    },
    {
      id: "diff",
      title: "Calculate the diff",
      explanation: "Toggle count 2 → 3. Watch the plan grow a single create.",
      duration: 2800,
      events: [
        { type: "highlight", nodeIds: ["config", "state", "plan"] },
        {
          type: "packet",
          from: "config",
          to: "plan",
          label: "desired",
          kind: "control",
          duration: 700,
        },
        {
          type: "packet",
          from: "state",
          to: "plan",
          label: "actual 2",
          kind: "data",
          delay: 200,
          duration: 700,
        },
        {
          type: "explain",
          text: "The engine subtracts. It does not “rebuild the fleet.”",
          delay: 1100,
        },
      ],
    },
    {
      id: "plan",
      title: "Plan",
      explanation: "A change order: +1 instance. The other two are not in the blast radius.",
      duration: 2400,
      events: [
        { type: "highlight", nodeIds: ["plan"] },
        { type: "state", nodeId: "plan", patch: { status: "Plan: 1 to add" } },
      ],
    },
    {
      id: "apply",
      title: "Apply calls the API",
      explanation: "Only now does a real request leave. Educational simulation — no account is touched.",
      duration: 2600,
      events: [
        { type: "highlight", nodeIds: ["plan", "api", "instances"] },
        {
          type: "packet",
          from: "plan",
          to: "api",
          label: "RunInstances max=1",
          kind: "http",
          duration: 900,
        },
        { type: "state", nodeId: "api", patch: { status: "202 accepted" }, delay: 950 },
        {
          type: "packet",
          from: "api",
          to: "instances",
          label: "i-0c3… created",
          kind: "response",
          delay: 1100,
          duration: 800,
        },
        { type: "state", nodeId: "instances", patch: { status: "3 running" }, delay: 1900 },
      ],
    },
    {
      id: "write-state",
      title: "State updated",
      explanation: "The new id is written back. The next plan starts from three, not two.",
      duration: 2400,
      events: [
        { type: "highlight", nodeIds: ["instances", "state"] },
        {
          type: "packet",
          from: "instances",
          to: "state",
          label: "write web[2] id",
          kind: "data",
          duration: 800,
        },
        { type: "state", nodeId: "state", patch: { status: "3 ids stored" }, delay: 850 },
        {
          type: "explain",
          text: "Config is the wish. State is the memory. The API is the world.",
          delay: 900,
        },
      ],
    },
  ],
};
